export type BiologyRuleNode = 'A0' | 'A1' | 'A2/A3' | 'A4' | 'A5';
export type BiologyRuleStatus = 'active' | 'candidate' | 'deprecated';
export type BiologyRuleSource = 'base' | 'boundary_feedback';
export type BiologyRuleEffect = 'useful' | 'unknown' | 'useless' | 'harmful';
export type BiologyRuleGovernance = 'core' | 'confirmed' | 'candidate' | 'experimental' | 'deprecated';
export type BiologyRuleInjectionMode = 'always' | 'top-k' | 'experiment-only' | 'off';
export type BiologyRuleRole =
  | 'avoid-comfort-zone'
  | 'target-weakness'
  | 'difficulty-preserver'
  | 'closure-gate'
  | 'direction-shift'
  | 'comparator-check';

export interface BiologyRule {
  id: string;
  node: BiologyRuleNode;
  status: BiologyRuleStatus;
  priority: number;
  knowledgeKeywords: string[];
  questionTypes: string[];
  logicPatterns: string[];
  triggerKeywords: string[];
  promptSnippet: string;
  source: BiologyRuleSource;
  evidenceCaseIds: string[];
  effect: BiologyRuleEffect;
  effectReason: string;
  // 治理字段（可选，旧规则无需立即补齐）。
  governance?: BiologyRuleGovernance;
  injectionMode?: BiologyRuleInjectionMode;
  role?: BiologyRuleRole;
  reportPath?: string;
  boundaryKey?: string;
  originAnalysisIds?: string[];
}

export const BIOLOGY_RULE_BANK: BiologyRule[] = [
  {
    id: 'base-a1-biology-calculation-priority-with-real-branching',
    node: 'A1',
    status: 'active',
    priority: 130,
    knowledgeKeywords: ['生物'],
    questionTypes: ['批量生题', '能力边界样本', '高防御生物题', '计算题'],
    logicPatterns: ['计算题优先', '真实分叉', '级联陷阱', '候选集合翻转', '主闭合量'],
    triggerKeywords: ['批量', '生物', 'V2', '计算题', '能力边界', '高难', '生题'],
    promptSnippet: '批量生物 V2 默认优先生成 calculation 维度；不要因为规避低区分度题型而降低计算题比例。合格计算题的最终目标优先是唯一数值/范围/中间闭合量或可由题设约束唯一确定的表达式/公式，且必须同时包含主闭合量、真实判断分叉和级联陷阱；禁止只靠增加背景、单位换算、资源账本或候选列表排除让题变长。若最终目标呈现为判断/选择/归因，计算仍必须是核心路径，并由主闭合量/判别量唯一推出结论；不得退化为纯机制题、单一容量或阈值直判。',
    source: 'boundary_feedback',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用户明确要求保留计算题优先；需要与“禁单资源FBA容量题”区分，避免误降计算题比例。',
    governance: 'core',
    injectionMode: 'always',
    role: 'difficulty-preserver',
  },
  {
    id: 'base-a1-avoid-single-resource-fba-capacity',
    node: 'A1',
    status: 'active',
    priority: 132,
    knowledgeKeywords: ['生物', '系统生物学', '合成生物学', '代谢工程', '辅因子', 'FBA', '13C-MFA'],
    questionTypes: ['计算题', '定量推理题', '能力边界样本', '高防御生物题'],
    logicPatterns: ['单资源账本退化', 'FBA候选直接打脸', 'NADPH容量上限', 'ATP余量上限', '酶容量上限', '释放阈值直接筛选'],
    triggerKeywords: ['FBA', '13C-MFA', 'NADPH', 'ATP', 'PntAB', 'Zwf', 'Rdr', 'kcat', '酶容量', '最高通量', '可行方案'],
    promptSnippet: '生成 FBA/13C-MFA/蛋白组/辅因子相关计算题时，禁止采用“纯FBA候选产物通量 + 一个NADPH/ATP/酶容量/PntAB/释放阈值约束 → 直接判断是否成立/最高可达通量/唯一可行方案”的骨架。这类骨架只需顺序计算资源账本或容量上限即可直接得解，区分度不足。若保留资源约束，它只能作为层1错误路径或辅助量；最终判定必须依赖状态可达性、历史分支、读出口径资格、候选集合翻转或多层动态机制耦合，并且 cascadeTrap 必须说明层1错解结果、层1正解解锁的层2变量、层2判别量和最终结论迁移。',
    source: 'boundary_feedback',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: 'FBA/NADPH/ATP/酶容量类题目区分度偏低，原因是它们退化为单资源账本或容量上限直接否定 FBA 候选。',
    governance: 'core',
    injectionMode: 'always',
    role: 'avoid-comfort-zone',
  },
  {
    id: 'base-a2a3-avoid-single-resource-fba-capacity-review',
    node: 'A2/A3',
    status: 'active',
    priority: 133,
    knowledgeKeywords: ['生物', '系统生物学', '合成生物学', '代谢工程', '辅因子', 'FBA', '13C-MFA'],
    questionTypes: ['计算题审核', '高防御生物题审核', '能力边界样本审核'],
    logicPatterns: ['单资源账本退化审核', '候选表筛选', '容量上限直判', '低区分度模式'],
    triggerKeywords: ['FBA', '13C-MFA', 'NADPH', 'ATP', 'PntAB', 'Zwf', 'Rdr', 'kcat', '酶容量', '最高通量', '可行方案'],
    promptSnippet: '审核 FBA/13C-MFA/蛋白组/辅因子题时，若标准解只需按顺序计算 NADPH供给、ATP余量、酶容量、PntAB供给或释放阈值，然后直接否定纯FBA候选或筛出唯一方案，应判为 difficultyIssue/depthIssue。这不是合格的动态分叉或级联陷阱。合格题必须让资源账本不能单独决定结论，而需要处理状态可达性、历史分支、读出口径资格、候选集合翻转或层1正确后才出现的层2判别量。',
    source: 'boundary_feedback',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于拦截易解的 FBA/辅因子单资源容量题。',
  },
  {
    id: 'base-a5-avoid-single-resource-fba-capacity-target-chain-check',
    node: 'A5',
    status: 'active',
    priority: 131,
    knowledgeKeywords: ['生物', '系统生物学', '合成生物学', '代谢工程', '辅因子', 'FBA', '13C-MFA'],
    questionTypes: ['盲解裁判', '能力边界样本裁判'],
    logicPatterns: ['单资源账本识别', '目标链未执行', '级联陷阱未触发'],
    triggerKeywords: ['FBA', '13C-MFA', 'NADPH', 'ATP', 'PntAB', '酶容量', '最高通量', '可行方案'],
    promptSnippet: '裁判 FBA/辅因子计算题时，若盲解只通过单一资源账本或容量上限计算就得到正确结论，不能算命中能力边界；必须检查其是否实际经历了候选集合翻转、状态可达性判断、读出口径资格判断或层1正解后才出现的层2判别量。',
    source: 'boundary_feedback',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于防止把低区分度的资源容量题误判为有效高防御题。',
  },
  {
    id: 'base-a1-batch-question-framing-diversity',
    node: 'A1',
    status: 'active',
    priority: 125,
    knowledgeKeywords: ['生物'],
    questionTypes: ['批量生题', '能力边界样本', '高防御生物题'],
    logicPatterns: ['问法多样性', '最终任务多样性', '计算维度去同质化', '计算服务于判断'],
    triggerKeywords: ['5道题', '批量', '多样性', '问法', '计算题', '求值', '表达式', '公式'],
    promptSnippet: '同一批次生成多道生物题时保持计算优先，但必须让计算维度和最终问法轮换：唯一数值、唯一范围、唯一中间闭合量、可由题设约束唯一确定的表达式/公式、阈值不等式、临界参数、定量瓶颈定位、由主闭合量支撑的判定结论等至少覆盖三类。可以都是以计算为核心的题；最终目标可以直接是主闭合量/范围/表达式/公式，也可以服务于后续判断或选择，但每题仍必须有真实判断分叉和级联陷阱。禁止五道题都以无分叉“求最终数值/浓度/比例/分子数/通量”为唯一目标；但不要把所有求值或表达式/公式目标都判为低价值，低价值的是给参数→套公式/函数→得终点的同骨架直算。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于解决V2批量生题题型和最终问法同质化，特别是多题都变成求值题的问题。',
  },
  {
    id: 'base-a2a3-batch-question-framing-review',
    node: 'A2/A3',
    status: 'active',
    priority: 126,
    knowledgeKeywords: ['生物'],
    questionTypes: ['批量题审核', '高防御生物题审核', '动态规则验收'],
    logicPatterns: ['同批同骨架识别', '最终问法重复', '装饰性换壳', '题型单一'],
    triggerKeywords: ['批量', '多样性', '问法', '最终问题', '求值', '表达式', '公式', '同类型'],
    promptSnippet: '审核批量生物题时，若同批多题都退化为无分叉“给参数→套公式/函数→得终点标量”，即使知识点、物种或单位不同，也必须标记多样性不足并要求重做。不要仅因最终目标是求值、范围、中间闭合量或表达式/公式就判为低价值；关键是它是否由真实分叉、状态池/读出口径/模型选择/边界条件共同唯一闭合，且是否包含级联陷阱。合格批次应在题型外观和最终问法上同时变化：至少覆盖唯一数值/范围/中间闭合量/表达式或公式/阈值不等式/临界参数/定量瓶颈定位/由主闭合量支撑的判定结论中的三类；不得用候选列表逐条排除或纯文字机制解释替代计算闭合。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于A2/A3拦截批量题问法重复和同骨架换壳。',
  },
  {
    id: 'base-a1-cross-domain-anti-formula-chain-substitution',
    node: 'A1',
    status: 'active',
    priority: 123,
    knowledgeKeywords: ['生物'],
    questionTypes: ['计算题', '定量推理题', '模型推理题', '能力边界样本', '高防御生物题'],
    logicPatterns: ['公式链式代入退化', '显式函数伪推理', '模型选择缺失', '状态边界缺失', '读出口径缺失'],
    triggerKeywords: ['公式', '函数', '传递函数', 'Kd', 'Km', 'Hill', '稳态', '分子数', '浓度', '比例', '通量', '占有率', '校正'],
    promptSnippet: '所有生物领域和题型都必须避免“完整公式/函数链已给、变量数值已给、答案只剩按顺序代入求末端数值”的退化题。允许最终目标是可由题设约束唯一确定的表达式/公式，但该表达式/公式必须来自模型选择、状态空间锁定、边界条件闭合或变量定义切换，而不是把题面已给函数改写一遍。定量信息必须制造模型选择、状态空间锁定、分母/读出口径、校正方向、可达性、机制竞争或证据资格中的实质分叉；若删除生物背景后仍只是多步算术或闭式函数链求值/改写，应重做题目骨架，不得靠增加小数、单位换算、多个中间变量或长题干伪装难度。但不要把“有公式”机械等同于低价值：若必须先完成热力学方向、变量资格、状态池归属或读出口径判断，且错误资格会改变结论，则应保留该真实分叉。相反，在酶学、代谢通量和生物物理定量题中，即使包含读出口径选择、总量到游离量校正或候选模型比较，只要正确读数/池归属已由题面显式提示，最终只是把候选参数代入完整公式并按单个残差或阈值判定，也应视为低区分度的公式链变体；需要增加真正的模型选择、可识别性或证据资格冲突。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于跨领域拦截显式公式链式代入伪推理，避免任何生物学科题退化为低层计算。',
    governance: 'core',
    injectionMode: 'always',
    role: 'avoid-comfort-zone',
  },
  {
    id: 'base-a2a3-cross-domain-anti-formula-chain-review',
    node: 'A2/A3',
    status: 'active',
    priority: 124,
    knowledgeKeywords: ['生物'],
    questionTypes: ['高防御生物题审核', '能力边界样本审核', '动态规则验收', '计算题审核'],
    logicPatterns: ['公式链式代入识别', '装饰性参数', '单终点数值退化', '目标逻辑未执行', '低区分度模式'],
    triggerKeywords: ['直接代入', '逐层代入', '公式', '函数', '最终数值', '稳态', '分子数', '浓度', '比例', '通量'],
    promptSnippet: '审核任何生物题时，若题干已经给出求解所需的完整公式/函数、全部变量定义和数值，标准解只需顺序代入得到一个终点数值、单一比例，或只是改写题面已给闭式表达式/公式，应判为depthIssue或difficultyIssue；即使步骤超过3步、单位很多或背景很专业也不合格。合格题必须存在至少一个不可由题面公式自动完成的生物推理分叉，例如模型假设选择、状态池归属、观测读数资格、竞争机制排除、动态可达性、分母定义或校正方向判断。若最终目标是表达式/公式，审核其形式是否由题设约束唯一确定，且是否需要真实模型选择、状态池归属、读出口径、边界条件或变量定义切换；满足则合格。审核时不要仅因题目提供 ΔG、Hill、Michaelis 或计量公式就判为公式链退化；若标准解必须先判定热力学方向、游离池/总池、读数资格、计量口径或状态空间，且错误选择会改变最终结论，则可保留为有效计算分叉。反之，若生物口径选择或游离量校正已由题干直接提示，标准解无需解决可识别性、状态空间、读数资格冲突或机制竞争，只需对候选参数逐一代入并按残差排序，则应判为防御不足。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于A2/A3跨题型验收，防止显式公式代入题通过长链条包装过审。',
  },
  {
    id: 'bio-boundary-a1-enzyme-thermo-kinetic-variable-qualification',
    node: 'A1',
    status: 'active',
    priority: 128,
    knowledgeKeywords: ['酶热力学', '酶动力学', 'Hill', 'Michaelis', 'ΔG', 'RTlnQ', 'NADH', 'NADPH', 'O2', '游离池', '活度'],
    questionTypes: ['酶学热力学定量推理题', '计算题', '能力边界样本'],
    logicPatterns: ['ΔG方向资格', '变量池资格', '游离池/总池区分', '活度变量锁定', '题设计量闭合'],
    triggerKeywords: ['ΔG', 'RTlnQ', 'Hill', 'Michaelis', '游离', '活度', 'NADH', 'NADPH', 'O2', '呼吸计量'],
    promptSnippet: '生成酶动力学×热力学×呼吸/还原当量计量题时，应设置至少一个变量资格分叉：例如总代谢物池、游离池、蛋白结合校正传感器读数、活度Q和酶调控位点可用配体不可直接互换。标准路径必须先用ΔG=ΔG°′+RTlnQ判定净方向是否允许，再把正确的游离/活度变量代入Hill或Michaelis式，并按题设给定的NADH/NADPH/O2或质子计量换算表观读数。禁止让答案自造未给出的TCA通量、底物生成上限或资源账本来替代题设指定的酶速率模型。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-18'],
    effect: 'useful',
    effectReason: '实测中出现用自造TCA/苹果酸通量上限替代题设SfcA热力学与Hill动力学模型的错误路径，说明变量资格和题设计量闭合能暴露能力边界。',
  },
  {
    id: 'bio-boundary-a2a3-enzyme-thermo-kinetic-variable-review',
    node: 'A2/A3',
    status: 'active',
    priority: 129,
    knowledgeKeywords: ['酶热力学', '酶动力学', 'Hill', 'Michaelis', 'ΔG', 'RTlnQ', 'NADH', 'NADPH', 'O2', '游离池', '活度'],
    questionTypes: ['酶学热力学定量题审核', '计算题审核', '能力边界样本审核'],
    logicPatterns: ['热力学方向审核', '变量池资格审核', '题设计量闭合审核', '自造通量识别'],
    triggerKeywords: ['ΔG', 'RTlnQ', 'Hill', 'Michaelis', '游离', '活度', 'TCA', 'P/O', '呼吸计量'],
    promptSnippet: '审核酶动力学×热力学×呼吸计量题时，必须检查标准解是否明确区分：ΔG方向资格、总池与游离池/活度、调节物与底物、动力学速率与上游代谢通量、题设还原当量计量与外部TCA/P/O计量。若答案只做公式代入且没有变量资格分叉，应判depthIssue；若答案擅自引入题干未给的代谢通路通量或底物上限来改写速率，应判validityIssue或criticalIssue。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-18'],
    effect: 'useful',
    effectReason: '用于防止修复阶段把题目改回低区分度舒适区，并捕捉该case中的错误路径。',
  },
  {
    id: 'bio-boundary-a1-reversible-transporter-haldane-apparent-parameter',
    node: 'A1',
    status: 'active',
    priority: 127,
    knowledgeKeywords: ['可逆酶', '膜转运体', 'Haldane', '详细平衡', 'Lineweaver-Burk', '表观参数', '膜电位', 'pH梯度', '电化学势'],
    questionTypes: ['膜转运蛋白可逆Michaelis-Menten参数闭合题', '可逆酶动力学题', '计算题'],
    logicPatterns: ['表观参数资格判断', 'Haldane闭合', '详细平衡闭合', '电化学驱动不得重复计入', '速率口径换算'],
    triggerKeywords: ['Haldane', '详细平衡', 'Lineweaver', 'Burk', '表观Km', '表观斜率', '膜电位', 'pH梯度', 'Keq', 'Vf', 'Vr'],
    promptSnippet: '生成可逆酶或膜转运体动力学题时，可设置Lineweaver-Burk截距/斜率、表观拟合斜率、膜电位或pH梯度等信息，但必须让解题者先判断哪些拟合量有资格作为真实模型参数。若题面给出Haldane、详细平衡或电化学平衡约束，至少一个看似可直接代入的表观斜率/表观Km应被热力学约束排除；电化学驱动应进入Keq或状态权重，不得再被重复乘入Vf/Vr，除非题干显式定义了条件化速率常数。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-18'],
    effect: 'useful',
    effectReason: '基础LB参数提取区分度不足，而把表观斜率当真实KP/Vr并错误修正Vf/Vr是稳定错误路径，适合生成参数资格和热力学闭合分叉。',
  },
  {
    id: 'bio-boundary-a2a3-reversible-transporter-haldane-apparent-parameter-review',
    node: 'A2/A3',
    status: 'active',
    priority: 128,
    knowledgeKeywords: ['可逆酶', '膜转运体', 'Haldane', '详细平衡', 'Lineweaver-Burk', '表观参数', '膜电位', 'pH梯度', '电化学势'],
    questionTypes: ['膜转运蛋白可逆Michaelis-Menten参数闭合题审核', '可逆酶动力学题审核', '计算题审核'],
    logicPatterns: ['表观参数误用审核', 'Haldane闭合审核', '热力学驱动重复计入审核', '质量归一化通量换算审核'],
    triggerKeywords: ['Haldane', '详细平衡', 'Lineweaver', 'Burk', '表观Km', '表观斜率', '膜电位', 'pH梯度', 'Keq', 'Vf', 'Vr'],
    promptSnippet: '审核可逆酶/膜转运体动力学题时，必须检查标准解是否显式区分表观拟合斜率、表观Km/Vmax与真实模型参数；若题面给出Haldane/详细平衡/电化学势约束，标准解应说明缺失参数由该约束闭合，而不是直接用表观斜率闭合。若答案把同一膜电位或pH梯度既用于Keq又额外指数修正Vf/Vr，或漏掉质量归一化速率到体积通量的口径换算，应标记为critical issue或depthIssue。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-18'],
    effect: 'useful',
    effectReason: '用于防止生成题或修复题退化为单纯LB代入，也识别同型的错误标准解。',
  },
  {
    id: 'bio-boundary-a1-enzymology-avoid-explicit-coupled-formula-residual-screen',
    node: 'A1',
    status: 'active',
    priority: 130,
    knowledgeKeywords: ['酶动力学', '热力学耦合', 'Hill', 'Michaelis', '残差筛选', 'K0.5', 'Vmax', '模型判别'],
    questionTypes: ['酶学热力学耦合模型机制判别题', '定量生物化学模型判别题', '计算题'],
    logicPatterns: ['显式耦合公式残差筛选避让', '参数可识别性', '局部池反卷积', '微观可逆性约束', '读数资格冲突'],
    triggerKeywords: ['Hill', 'Michaelis', 'K0.5', 'Vmax', '残差', '候选模型', '游离底物', 'Haldane', '详细平衡'],
    promptSnippet: '生成酶动力学×热力学耦合机制判别题时，禁止只给出完整Hill/Michaelis-Menten/热力学驱动力公式、全部数值、两个候选K0.5或Vmax，然后要求逐一代入并按单个Jobs残差选择机制。若保留计算模型，至少让一个关键量必须通过实验读出口径资格、局部/全池辅因子反卷积、总底物/游离底物状态归属、Haldane/详细平衡约束、参数可识别性或相邻机制排除来闭合；不得把正确读数或正确池归属直接写成显式提示。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-18'],
    effect: 'useful',
    effectReason: '显式读出口径选择、游离底物校正、热力学项和残差比已属可稳定求解范围，说明该骨架区分度不足。',
  },
  {
    id: 'bio-boundary-a2a3-enzymology-explicit-residual-screen-review',
    node: 'A2/A3',
    status: 'active',
    priority: 130,
    knowledgeKeywords: ['酶动力学', '热力学耦合', 'Hill', 'Michaelis', '残差筛选', 'K0.5', 'Vmax', '模型判别'],
    questionTypes: ['酶学定量机制判别题审核', '定量生物化学模型判别题审核', '计算题审核'],
    logicPatterns: ['显式公式链残差筛选审核', '低区分度模式识别', '参数可识别性审核', '读数可比性审核'],
    triggerKeywords: ['Hill', 'Michaelis', 'K0.5', 'Vmax', '残差', '候选模型', '游离底物', 'Haldane', '详细平衡'],
    promptSnippet: '审核酶动力学×热力学耦合题时，若标准答案的核心路径是：题面外显指定读出口径或池归属→总量换算游离量→代入已给Hill/热力学公式→对两个候选参数计算预测值→用单个观测残差筛选机制，应标记为difficultyIssue或fallsIntoAvoidPattern。合格修复应让结论依赖参数可识别性、局部池反卷积、Haldane/详细平衡一致性、读数可比性或相邻机制排除，而不是增加小数、单位换算或更多候选参数。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-18'],
    effect: 'useful',
    effectReason: '该case数值链较长但可被稳定求解，reviewer必须检查是否仍是显式公式链残差筛选。',
  },
  {
    id: 'base-a1-gene-circuit-transfer-function-anti-substitution',
    node: 'A1',
    status: 'active',
    priority: 121,
    knowledgeKeywords: ['系统生物学', '合成生物学', '基因回路拓扑', '传递函数', '基因线路', 'gene circuit', 'transfer function'],
    questionTypes: ['系统生物学基因回路题', '传递函数机制判别题', '合成生物学动态系统题'],
    logicPatterns: ['传递函数不得链式代入', '机制判别', '动态边界锁定', '读出可识别性', 'retroactivity与生长稀释'],
    triggerKeywords: ['传递函数', 'transfer function', 'IPTG', '启动子占有度', 'GFP', '稳态', '平台', 'Hill', '级联', '基因回路'],
    promptSnippet: '生成“基因回路拓扑×传递函数”题时，严禁把每个节点的稳态函数、输入浓度和单位全部给出后只要求逐层代入求末端GFP/报告分子数。传递函数必须用于区分竞争机制或动态边界：至少引入响应时标、初始状态/迟滞、阈值窗口、retroactivity、宿主负载/生长稀释、单细胞分布或读出校准中的两类约束，并要求判断哪个稳态可达、哪个通道读数有资格比较或哪个拓扑解释被排除。若最终仍是闭式函数链式求数值，应改写题骨架而非增加装饰参数。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于拦截系统生物学-基因回路拓扑×传递函数退化为显式稳态公式计算题。',
  },
  {
    id: 'base-a2a3-gene-circuit-transfer-function-review',
    node: 'A2/A3',
    status: 'active',
    priority: 122,
    knowledgeKeywords: ['系统生物学', '合成生物学', '基因回路拓扑', '传递函数'],
    questionTypes: ['高防御生物题审核', '系统生物学题审核', '动态规则验收'],
    logicPatterns: ['链式代入识别', '装饰性动力学参数', '目标逻辑未执行', '单终点数值退化'],
    triggerKeywords: ['传递函数', 'IPTG', 'GFP', '稳态分子数', '平台', '逐层代入', '级联'],
    promptSnippet: '审核“基因回路拓扑×传递函数”题时，若题干已给完整稳态传递函数和输入数值，答案只需按A→B→C→G顺序计算最终报告分子数，即使包含多个公式或小数参数，也必须判为depthIssue。合格题必须迫使解题者处理动态可达性、时标顺序、阈值跨越、retroactivity、负载稀释、单细胞异质性或读出映射中的实质分叉；只把这些词作为背景而不改变解题路径也不合格。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于A2/A3验收并重做传递函数链式代入伪动力学题。',
  },
  {
    id: 'base-a1-equal-difficulty-direction-expansion',
    node: 'A1',
    status: 'active',
    priority: 109,
    knowledgeKeywords: ['生物'],
    questionTypes: ['能力边界样本', '高防御生物题', '能力边界题'],
    logicPatterns: ['等难扩展', '多线索闭合', '相邻机制干扰', '不降难度'],
    triggerKeywords: ['能力边界', '方向', '扩展', '难度', '干扰', '闭合'],
    promptSnippet: '扩展生物出题方向时必须做等难迁移：保留当前题型的推理层级、判断分叉数、隐含约束数和诱惑性错误路径强度；只能更换介入变量、现象组合、错误归因入口或相邻机制干扰，不得把原高防御题降级为单现象→单机制、单指标趋势判断或直接概念辨析。题面应形成“多线索但答案闭合”：至少两条观测/条件共同排除竞争机制，且干扰机制必须来自同层级相邻机制。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于参考化学扩展生物能力边界方向时防止因控发散而降低原有生物题难度。',
  },
  {
    id: 'base-a2a3-equal-difficulty-direction-review',
    node: 'A2/A3',
    status: 'active',
    priority: 113,
    knowledgeKeywords: ['生物'],
    questionTypes: ['高防御生物题审核', '能力边界样本审核'],
    logicPatterns: ['等难扩展验收', '难度退化', '多线索闭合', '相邻机制干扰'],
    triggerKeywords: ['能力边界', '方向', '扩展', '难度', '干扰', '闭合'],
    promptSnippet: '审核扩方向题时必须检查是否发生难度退化：若题目把原有多步推理、隐含条件、判断分叉或诱惑性错误路径简化成单点机制判断/单指标变化/直接概念辨析，即使答案唯一也必须进入 difficultyIssues 或 depthIssues。合格题应保留原推理层级，并通过多条观测线索闭合答案、用同层级相邻机制制造非显然干扰。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于A2/A3拦截“为防发散而简化题目”的退化题。',
  },
  {
    id: 'base-a5-equal-difficulty-target-chain-check',
    node: 'A5',
    status: 'active',
    priority: 111,
    knowledgeKeywords: ['生物'],
    questionTypes: ['能力边界样本裁判', '盲解裁判'],
    logicPatterns: ['目标链执行', '难度退化识别', '相邻机制排除'],
    triggerKeywords: ['能力边界', '方向', '扩展', '难度', 'reasoningValid'],
    promptSnippet: '裁判扩方向题时，不能只看最终答案是否唯一；还要检查盲解是否执行了原设目标链中的多线索闭合、竞争机制排除和隐含约束识别。若题目本身已退化为单线索直接判断，或盲解跳过相邻机制排除却碰巧答对，不得判定为有效的能力边界命中。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于A5区分真正等难的能力边界题与被简化后的低价值题。',
  },
  {
    id: 'base-a1-noncalculation-anti-checklist-reasoning',
    node: 'A1',
    status: 'active',
    priority: 116,
    knowledgeKeywords: ['生物'],
    questionTypes: ['结构约束推理', '调控网络推理', '阈值逻辑推理', '遗传推理', '能力边界样本'],
    logicPatterns: ['反清单匹配', '隐性框架选择', '跨通道参照冲突', '证据可识别性边界'],
    triggerKeywords: ['cryo-EM', 'HDX', 'TROSY', 'BRET', '电压', '证据', '结构', '推理', '非计算'],
    promptSnippet: '非计算推理题禁止退化为显式证据准入表/逐条质控清单审计。不得把“可接收条件、阈值窗口、登记栏、报告口径”直接写成题面清单后要求逐条判断；必须把标准转化为隐性框架选择或跨通道参照冲突：例如先从数据重构真实中间状态、识别缺失校准导致的不可识别边界、判定两个证据通道是否在同一状态空间/同一批次/同一参照系中可比较，再决定证据层级。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '非计算推理题若以显式证据清单审计呈现，区分度基本丧失，需要改成隐性框架与跨通道冲突推理。',
  },
  {
    id: 'base-a2a3-noncalculation-checklist-review',
    node: 'A2/A3',
    status: 'active',
    priority: 117,
    knowledgeKeywords: ['生物'],
    questionTypes: ['结构约束推理审核', '调控网络推理审核', '阈值逻辑推理审核', '能力边界样本审核'],
    logicPatterns: ['清单审计退化', '标准外显', '隐性框架缺失', '跨通道冲突缺失'],
    triggerKeywords: ['cryo-EM', 'HDX', 'TROSY', 'BRET', '电压', '证据', '结构', '推理', '非计算'],
    promptSnippet: '审核非计算推理题时，若答案路径完全等同于逐条套用题面明示的准入条件/登记表/报告口径/质控窗口，且不需要先完成隐性框架选择、参照系重构、状态空间锁定或跨通道可比性判断，才判为 depthIssue；若已有真实中间状态重构，则优先在 correctionHints 中建议减少标准外显、增强定量/校正承诺，不要一票否决。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于A2/A3拦截“非计算推理=证据清单审计”的低价值题。',
  },
  {
    id: 'base-a5-noncalculation-target-chain-check',
    node: 'A5',
    status: 'active',
    priority: 114,
    knowledgeKeywords: ['生物'],
    questionTypes: ['能力边界样本裁判', '盲解裁判'],
    logicPatterns: ['清单匹配无效', '目标链执行', '参照系重构', '可识别性边界'],
    triggerKeywords: ['cryo-EM', 'HDX', 'TROSY', 'BRET', '电压', '证据', '结构', 'reasoningValid'],
    promptSnippet: 'A5裁判非计算推理题时，若盲解只是逐条复述题面准入标准并匹配数据，即使结论正确也不能算命中目标能力边界；必须检查其是否实际完成了真实状态重构、跨通道参照系换算、证据可比性判断或不可识别边界判定。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于避免把清单匹配型正确答案误判为有效推理边界。',
  },
  {
    id: 'base-metabolic-flux-not-fitness',
    node: 'A1',
    status: 'active',
    priority: 92,
    knowledgeKeywords: ['代谢通量', '糖异生', '别构', '适应度', '能量稳态', '无效循环'],
    questionTypes: ['代谢稳态推断题', '结构-功能-适应度跨层级题'],
    logicPatterns: ['局部通量增强不等于整体适应度提升', '代谢反馈失控', '结构到生理跨层级整合'],
    triggerKeywords: ['通量增强', '存活', '适应', 'ATP/ADP', '无效循环', '碳架'],
    promptSnippet: '若题目涉及代谢通量与适应度，必须让学生检验能量成本、无效循环和碳架稳态；禁止把局部通量增强直接当作生长/存活优势。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '来自生物侧高频跨层级误判，等待更多样本验证。',
  },
  {
    id: 'base-open-system-steady-state-priority',
    node: 'A1',
    status: 'active',
    priority: 90,
    knowledgeKeywords: ['开放系统', '稳态通量', '液泡', '渗透调节', '转运', '总量守恒'],
    questionTypes: ['开放系统稳态题', '通量-总量冲突判断题'],
    logicPatterns: ['开放系统稳态优先于封闭系统总量守恒', '阈值外排分支判断', '先验自洽性检查'],
    triggerKeywords: ['开放系统', '稳态', '持续输入', '外排', '总量', '守恒'],
    promptSnippet: '若系统存在持续输入/外排或跨膜交换，必须先判定开放系统通量稳态，再决定总量守恒是否仍可作为约束；禁止直接把当前总量沿用到突变后稳态。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于稳定命中开放系统与封闭系统混淆。',
  },
  {
    id: 'base-threshold-state-machine-trigger-variable',
    node: 'A1',
    status: 'active',
    priority: 94,
    knowledgeKeywords: ['迟滞', '状态机', 'NADPH', 'RET', '激活阈值', '历史依赖'],
    questionTypes: ['阈值迟滞题', '状态依赖题', '时间序列扰动题'],
    logicPatterns: ['先分离触发变量再判状态切换', '未跨阈值不得判激活', '历史路径决定状态'],
    triggerKeywords: ['θ_on', 'θ_off', '迟滞', '激活', '未跨阈值', '历史路径'],
    promptSnippet: '若题目涉及阈值、迟滞或状态切换，必须让学生先识别真正的触发变量并检验是否跨越阈值；禁止把总池变化、背景叙事或当前输入值直接等同于状态切换。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于拦截“未跨阈值却判激活”“只看终态不看历史”的常见错误。',
  },
  {
    id: 'base-apparent-vs-true-biophysical-readout',
    node: 'A1',
    status: 'active',
    priority: 95,
    knowledgeKeywords: ['OCR', '真实质子电导', 'AOX', '表观读数', '离子通量', '门控'],
    questionTypes: ['生物物理综合题', '表观量与真实量解耦题'],
    logicPatterns: ['表观代谢读数不等于真实离子通量', '必要条件不等于充分条件', '非泵耗氧校正'],
    triggerKeywords: ['OCR', 'AOX', '真实电导', '表观', '必要非充分', '门控'],
    promptSnippet: '若题目用表观读数推真实机制，必须插入“表观量→真实量”的校正层，并检验必要条件与充分条件的区别；禁止把表观 OCR、总电流或总体信号直接当作真实门控/通量。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于提高膜生物物理和代谢读数类题目的定向性。',
  },
  {
    id: 'base-biochem-parameter-no-double-count',
    node: 'A1',
    status: 'active',
    priority: 88,
    knowledgeKeywords: ['酶动力学', '抑制比例', '通量源项', 'Hill', '遗传扰动', 'NADH', '表观拟合参数', 'Haldane', '膜电位', 'pH梯度', '电化学势', 'Km', 'KP', 'Vf', 'Vr'],
    questionTypes: ['代谢稳态计算题', '多酶通量参数解析题', '可逆转运酶动力学题', '膜转运蛋白通量解析题'],
    logicPatterns: ['题干参数语义合并', '禁止重复计入残余抑制', '表观参数与真实参数分层', '热力学驱动不得重复计入', 'Haldane闭合', '先检验上游源项再看代偿分支'],
    triggerKeywords: ['70%', '残余抑制', '活性恢复', '源通量', '希尔函数', 'Haldane', 'Lineweaver', 'Burk', '表观Km', '膜电位', 'pH梯度', 'Keq'],
    promptSnippet: '若题目给出恢复比例、残余抑制、表观拟合参数、Haldane约束、膜电位/pH梯度或电化学势等多类参数，必须让答案先完成参数语义分层：哪些是观测表观量，哪些是真实模型参数，哪些只定义平衡常数或状态权重。禁止把同一机制驱动既用于热力学约束又重复乘入单向速率常数，或把表观斜率直接当真实Km/KP，除非题干明确授权。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '针对生物化学参数重复计入的稳定错误；边界分析用例 显示同类错误会迁移到可逆转运酶、Haldane约束和膜电位驱动题。',
  },
  {
    id: 'base-a1-fitting-operational-definition',
    node: 'A1',
    status: 'active',
    priority: 107,
    knowledgeKeywords: ['生物', '动力学', '剂量反应', '时间序列', '拟合'],
    questionTypes: ['定量生物题', '结构生物学定量题', '酶动力学题', '生长曲线题'],
    logicPatterns: ['多点拟合口径锁定', '观测通道唯一', 'operational definition', '参数估计闭合'],
    triggerKeywords: ['拟合', 'fit', 'kobs', 'k_obs', '单指数', '双指数', 'Hill', 'EC50', 'IC50', '半衰期', '增长率', '时间点'],
    promptSnippet: '凡题目由两个及以上观测点拟合或估计同一中间变量，必须在题干锁定 operational definition：纳入哪些点、模型参数是否固定、损失函数/加权方式、剔除规则和单位；若不想外显复杂口径，必须改成单点定义、删除竞争观测，或把额外观测改为有唯一弃用理由的质控/陷阱参数。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '跨知识点防止多观测点拟合同一中间变量时出现多条自洽计算路径。',
  },
  {
    id: 'base-review-structural-defense-rubric-biology',
    node: 'A2/A3',
    status: 'active',
    priority: 100,
    knowledgeKeywords: ['生物'],
    questionTypes: ['高防御生物题审核'],
    logicPatterns: ['判断分叉', '隐含条件', '表观量到真实量', '历史依赖', '开放系统边界'],
    triggerKeywords: ['生物'],
    promptSnippet: '审核时必须确认题目是否真的存在判断分叉、隐含条件、不可跳过的中间还原层，以及是否把开放系统/状态机/表观量与真实量的边界钉死；任一缺失都应进入 depthIssues。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '生物侧高防御审核基线。',
  },
  {
    id: 'base-a5-target-logic-check-biology',
    node: 'A5',
    status: 'active',
    priority: 84,
    knowledgeKeywords: ['生物'],
    questionTypes: ['能力边界样本裁判', '盲解裁判'],
    logicPatterns: ['目标解题逻辑执行检查', '结论正确但关键还原层缺失'],
    triggerKeywords: ['生物'],
    promptSnippet: '裁判需判断答案是否真的执行了目标生物推理链；即使最终结论一致，只要跳过关键的池量分离、状态机触发、开放系统边界或表观量校正层，也不得判定 reasoningValid。',
    source: 'base',
    evidenceCaseIds: [],
    effect: 'unknown',
    effectReason: '用于把“结论碰巧正确”与“推理有效”分开。',
    governance: 'core',
    injectionMode: 'always',
    role: 'closure-gate',
  },
  {
    id: 'boundary-b-a0-biology-boundary-dimension-planning',
    node: 'A0',
    status: 'active',
    priority: 96,
    knowledgeKeywords: ['HDX-MS', '结构生物学', '生物物理学', 'GPCR', '膜蛋白', '自由基对', '液接电位', '单细胞', 'FACS', 'bulk RNA', '遗传学'],
    questionTypes: ['能力边界规划', '知识点维度规划', '能力边界样本'],
    logicPatterns: ['模型选择', '状态空间锁定', '统计口径推导', '证据冲突排序', '必要条件链闭合', '参数语义乘除方向判断'],
    triggerKeywords: ['反向交换', '理论可交换池', '回收率', '端元', '局部分辨率', 'Q-score', 'half-map', '状态空间', '容差', '质控', '目标群体'],
    promptSnippet: '规划知识点维度时，优先把显式公式代入升级为模型选择、状态空间锁定、统计口径推导、证据冲突排序、必要条件链闭合或参数语义乘除方向判断；避免继续规划已属低区分度的单层显式公式/阈值题。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11', 'boundary-analysis-2026-06-10'],
    effect: 'useful',
    effectReason: '来自能力边界分析的A0/A1方向总结，用于让A0提前选择可触发薄弱环节的测试维度。',
  },
  {
    id: 'boundary-b-a1-hdx-back-exchange-pool-calibration',
    node: 'A1',
    status: 'active',
    priority: 108,
    knowledgeKeywords: ['HDX-MS', '结构生物学', '膜蛋白构象群体比例', '反向交换', '理论可交换池', '回收率校正'],
    questionTypes: ['结构生物学定量题', 'HDX-MS构象比例校正题', '定量生物物理模型检验题'],
    logicPatterns: ['理论可交换池与端元标尺语义分离', '反向交换回收率校正', '观测读数不得直接替代构象比例', '先锁定分母再计算比例'],
    triggerKeywords: ['HDX', 'back-exchange', '反向交换', '回收率', 'fully deuterated', 'undeuterated', 'centroid', '端元', '可交换池', '构象比例'],
    promptSnippet: '生成HDX-MS或膜蛋白构象比例题时，必须设置“原始uptake/centroid→反向交换校正→理论可交换池/端元标尺→构象比例”的不可跳过链路；禁止把cryo-EM occupancy、B-factor、单通道占空比或未校正HDX读数直接替代真实构象比例。若用多时间点拟合kobs，必须同时锁定纳入时间点、平台/端元是否固定、拟合准则和单位。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11'],
    effect: 'useful',
    effectReason: '边界分析显示HDX-MS反向交换变量语义分离、理论可交换池和回收率校正是薄弱环节，适合直接进入A1生题约束。',
  },
  {
    id: 'boundary-b-a1-structural-evidence-necessary-chain',
    node: 'A1',
    status: 'active',
    priority: 106,
    knowledgeKeywords: ['结构生物学', 'GPCR', '膜蛋白', 'cryo-EM', 'HDX', 'NMR', 'GIRK', 'β-arrestin'],
    questionTypes: ['多模态结构功能判定题', '膜蛋白变构证据分级题', '结构功能闭合题'],
    logicPatterns: ['证据冲突排序', '必要条件链闭合', '反多数投票', '局部结构质量审计', '功能读数不能补足结构证据缺口'],
    triggerKeywords: ['局部分辨率', 'Q-score', 'map-model CC', 'half-map', 'HDX肽段', '微开关', '功能读数', '多数投票', '必要条件'],
    promptSnippet: '生成结构-功能耦合题时，应使用必要条件链而不是多数投票：局部结构真实性、配体占有、样品完整性、构象类别排他和同批功能闭合必须分别定义；HDX肽段保护不得直接推出微开关状态，功能读数不得补足低可信结构证据。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-10'],
    effect: 'useful',
    effectReason: '本次报告多次指出结构生物学题需要从实验罗列升级为局部审计、证据分级和功能闭合。',
  },
  {
    id: 'boundary-b-a1-state-space-endpoint-consistency',
    node: 'A1',
    status: 'active',
    priority: 104,
    knowledgeKeywords: ['生物物理学', '膜蛋白变构模型', 'HDX构象比例', 'MWC', '端元', '状态空间'],
    questionTypes: ['模型一致性检验题', '构象比例校验题', '定量生物物理模型题'],
    logicPatterns: ['题干状态空间锁定', '端元读数独立换算', '容差阈值判断', '禁止新增隐变量逃逸'],
    triggerKeywords: ['MWC', '开态比例', '端元', '容差', '状态空间', '未知变量', 'HDX比例', '一致性检验'],
    promptSnippet: '生成膜蛋白变构模型或HDX比例校验题时，必须锁定题干指定状态空间，要求先按模型计算目标状态比例，再由端元读数独立换算同一比例并用容差判断；禁止允许答案通过新增隐变量或扩展状态空间绕开一致性检验。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-10'],
    effect: 'useful',
    effectReason: '边界分析显示常见错误路径是用貌似合理的额外构象状态绕开题干模型，导致结论正确但推理无效。',
  },
  {
    id: 'boundary-b-a2a3-boundary-realization-review',
    node: 'A2/A3',
    status: 'active',
    priority: 112,
    knowledgeKeywords: ['HDX-MS', '结构生物学', '生物物理学', '单细胞', 'FACS', 'bulk RNA', '遗传学', '生物'],
    questionTypes: ['高防御生物题审核', '能力边界样本审核', '动态规则验收'],
    logicPatterns: ['规则兑现审查', '旧题换壳', '装饰性干扰参数', '中间还原层缺失', '目标逻辑未执行'],
    triggerKeywords: ['反向交换', '局部分辨率', '状态空间', '回收率', '质控', '端元', '必要条件', '参数语义', '证据冲突'],
    promptSnippet: '审核与修复时必须验收动态规则是否真正落实：每个复杂参数都要改变模型选择、分母定义、校正方向、读数资格或证据权重；若只是术语堆叠、旧题换壳、装饰性干扰或终局仍回到单步公式，应判为depthIssue并重做题目骨架。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11', 'boundary-analysis-2026-06-10'],
    effect: 'useful',
    effectReason: '本次报告要求A2/A3检查A1规则是否钉死关键还原层，防止题目退化为旧模板。',
  },
  {
    id: 'boundary-b-a5-target-chain-even-when-answer-matches',
    node: 'A5',
    status: 'active',
    priority: 110,
    knowledgeKeywords: ['HDX-MS', '结构生物学', '生物物理学', '遗传学', '生物工程学', '生物'],
    questionTypes: ['盲解裁判', '答案一致性裁判', '能力边界样本裁判'],
    logicPatterns: ['答案一致但关键还原层缺失', '模型假设被改写', '证据边界被越权', '参数语义方向错误'],
    triggerKeywords: ['结论正确', '推理路径错误', '新增隐变量', '跳过', '未校正', '直接代入', '过度结论', '目标逻辑'],
    promptSnippet: 'A5即使看到盲解答案与标准结论一致，也必须继续检查是否执行目标链：是否完成池量/状态空间/端元/回收率/质控门控/证据边界/参数乘除方向等关键还原层；若结论一致但改写模型或跳过目标逻辑，应判 reasoningValid=false。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-10'],
    effect: 'useful',
    effectReason: '本次报告反复出现“结论正确但关键推理链错误”，因此需要让A5答案一致时仍审查目标逻辑。',
  },
  {
    id: 'boundary-legacy-a1-isotope-pool-weighted-deconvolution',
    node: 'A1',
    status: 'active',
    priority: 107,
    knowledgeKeywords: ['13C-MFA', 'LC-MS', 'bulk M+', '单细胞', '细胞异质性', '亚群比例', '代谢物池量'],
    questionTypes: ['稳定同位素示踪题', '单细胞群体反卷积题', '代谢通量池量加权题'],
    logicPatterns: ['细胞比例不等于代谢物池贡献', '先按单位细胞池量反卷积', 'bulk同位素峰不能直接平均'],
    triggerKeywords: ['13C', 'M+2', 'M+3', 'bulk', 'LC-MS', '亚群', '分选', '单位细胞', '池量', '反卷积'],
    promptSnippet: '生成13C-MFA、LC-MS或bulk同位素峰题时，必须设置“细胞比例 × 单位细胞代谢物池量”的贡献权重，要求先反卷积隐藏亚群标记再进入通量模型；禁止直接按细胞比例平均bulk M+x，除非题干明示单位细胞池量相等。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-05'],
    effect: 'useful',
    effectReason: '历史分析反复显示细胞比例、代谢物池量和bulk同位素峰之间的参照总体转换是薄弱环节，适合进入A1生成约束。',
  },
  {
    id: 'boundary-legacy-a2a3-isotope-pool-weighted-review',
    node: 'A2/A3',
    status: 'active',
    priority: 105,
    knowledgeKeywords: ['13C-MFA', 'LC-MS', 'bulk M+', '单细胞', '细胞异质性', '亚群比例', '代谢物池量'],
    questionTypes: ['稳定同位素示踪题审核', '代谢通量反卷积题审核'],
    logicPatterns: ['检查池量权重是否改变分母', '检查bulk读数是否可直接平均', '检查隐藏亚群是否必须反卷积'],
    triggerKeywords: ['13C', 'M+2', 'M+3', 'bulk', 'LC-MS', '亚群', '单位细胞', '池量', '反卷积'],
    promptSnippet: '审核13C-MFA或bulk LC-MS题时，必须检查题目是否真的迫使解题者使用单位细胞池量权重；若细胞比例平均即可得到答案，或题干未给足池量/贡献权重导致不可唯一反卷积，应进入depthIssues或validityIssues。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-05'],
    effect: 'useful',
    effectReason: '与A1规则配套，用于防止生成端只堆叠同位素术语但没有真正形成池量反卷积分叉。',
  },
  {
    id: 'boundary-legacy-a1-electrophysiology-reference-frame',
    node: 'A1',
    status: 'active',
    priority: 106,
    knowledgeKeywords: ['液接电位', 'LJP', 'GHK', 'Nernst', '膜片钳', '局部活度', '界面电势', '离子通道'],
    questionTypes: ['电生理参考系校正题', '离子通道通透性反演题', '局部活度Nernst题'],
    logicPatterns: ['先符号化电位参照系', '校正层级只能使用一次', '局部活度边界不得二次修正'],
    triggerKeywords: ['Vrec', 'Vtrue', 'Vm', 'pipette', 'bath', 'cis', 'trans', 'LJP', 'GHK', 'Nernst', '局部活度', 'Boltzmann'],
    promptSnippet: '生成液接电位、GHK或Nernst题时，必须让题目绑定Vread/Vtrue/Vm/LJP与实验坐标系的代数关系，并设置校正层级边界；若题干已给孔口局部活度作为GHK边界，禁止再让界面电势或PB修正被二次计入。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-05'],
    effect: 'useful',
    effectReason: '多份旧报告显示电生理题的高价值弱点在参照系、LJP方向和局部活度层级，而不是单一Nernst公式。',
  },
  {
    id: 'boundary-legacy-a2a3-electrophysiology-reference-frame-review',
    node: 'A2/A3',
    status: 'active',
    priority: 106,
    knowledgeKeywords: ['液接电位', 'LJP', 'GHK', 'Nernst', '膜片钳', '局部活度', '界面电势', '离子通道'],
    questionTypes: ['电生理参考系校正题审核', '离子通道通透性反演题审核'],
    logicPatterns: ['审查电位符号约定', '审查LJP校正方向', '审查局部活度是否重复修正'],
    triggerKeywords: ['Vrec', 'Vtrue', 'Vm', 'pipette', 'bath', 'cis', 'trans', 'LJP', 'GHK', 'Nernst', '局部活度'],
    promptSnippet: '审核电生理题时，必须要求标准答案显式写出记录电位、真实膜电位和LJP的关系；若题目没有钉死符号约定，或把局部活度/界面电势/GHK边界重复校正，应判为critical issue。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-05'],
    effect: 'useful',
    effectReason: '与A1电生理规则配套，防止题目退化为显式单步Nernst/GHK代入。',
  },
  {
    id: 'boundary-b-a1-membrane-gating-reference-frame-binding',
    node: 'A1',
    status: 'active',
    priority: 118,
    knowledgeKeywords: ['膜蛋白', '离子通道', '膜片钳', '液接电位', 'LJP', '零点偏置', '门控热力学', '开闭比'],
    questionTypes: ['膜蛋白变构定量题', '离子通道门控题', '电生理参考系校正题'],
    logicPatterns: ['名义电压与真实膜电位绑定', '已测开闭比语义锁定', '零点偏置进入门控热力学校正', '相对电压差修正'],
    triggerKeywords: ['名义电压', '命令电压', '真实膜电位', '液接电位', 'LJP', '零点偏置', 'offset', '开/闭比', '开闭比', 'Popen', 'Kd', '门控'],
    promptSnippet: '生成膜蛋白/离子通道门控题时，若涉及电压依赖开闭比或配体耦联权重，必须明确区分名义指令电压、真实膜电位、液接电位、放大器零点偏置、测得开/闭比所在电压和目标外推电压。题目应让校正后的电位进入状态空间或统计热力学权重；若给定的是某电压处实测开/闭比，应以相对电压差修正，禁止默认其为零电压平衡常数，也禁止把零点偏置视为与门控平衡无关的纯显示误差。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11'],
    effect: 'useful',
    effectReason: '能力边界分析显示，简单两态构象和配体Kd权重区分度不足，而膜片记录参考系、零点偏置和已测开闭比语义是稳定失败点，适合作为A1生成端通用约束。',
  },
  {
    id: 'boundary-b-a2a3-membrane-gating-reference-frame-review',
    node: 'A2/A3',
    status: 'active',
    priority: 119,
    knowledgeKeywords: ['膜蛋白', '离子通道', '膜片钳', '液接电位', 'LJP', '零点偏置', '门控热力学', '开闭比'],
    questionTypes: ['膜蛋白变构题审核', '离子通道门控题审核', '电生理参考系审核'],
    logicPatterns: ['审核参考系代数关系', '审核已测开闭比语义', '审核零点偏置资格', '审核符号歧义'],
    triggerKeywords: ['名义电压', '命令电压', '真实膜电位', '液接电位', 'LJP', '零点偏置', 'offset', '开/闭比', '开闭比', 'Popen', '门控'],
    promptSnippet: '审核膜蛋白/离子通道门控题时，必须检查标准答案是否显式写出名义电压、真实膜电位、LJP/液接电位、零点偏置和目标外推电压之间的代数关系；若把某电压处实测开/闭比误当零电压平衡常数，或声称零点偏置不影响用于门控热力学校正的真实膜电位，应判为critical issue。若参考系符号约定未钉死导致多解，也必须要求重写题干。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11'],
    effect: 'useful',
    effectReason: '与A1膜蛋白门控参考系规则配套，防止审核端放过“公式链正确但参考系语义错误”的题。',
  },
  {
    id: 'boundary-b-a1-systems-biology-readout-operational-definition',
    node: 'A1',
    status: 'active',
    priority: 115,
    knowledgeKeywords: ['系统生物学', '合成生物学', '基因回路', '动态阈值', '迟滞', '报告蛋白', '读出口径'],
    questionTypes: ['系统生物学动态题', '合成生物学基因回路题', '多读出通道判定题'],
    logicPatterns: ['operational definition锁定', '读出口径资格', '成熟报告滞后', '即时状态与稳态窗口区分', '状态历史重构'],
    triggerKeywords: ['MS2', 'nascent RNA', '成熟荧光', 'GFP', 'bulk', '流式', '阈值', '状态边界', '迟滞', '稳态窗口', '读出'],
    promptSnippet: '生成系统生物学/合成生物学动态题时，阈值和状态边界必须服从题面 operational definition。若同时存在 MS2/nascent RNA、成熟报告蛋白荧光、bulk蛋白、流式门控或传感器读数，必须要求先判定读数代表即时转录状态、成熟后滞后输出、稳态窗口还是亚群分布；禁止把成熟报告蛋白短时扰动后的数值直接等同于当前转录状态或阈值占据度，除非题干给出成熟动力学达到稳态或可逆推的动态校正模型。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11'],
    effect: 'useful',
    effectReason: '边界分析显示，系统生物学动态题的稳定弱点在读出口径资格、时间尺度和阈值定义，而不是单纯Hill函数或显式阈值代入。',
  },
  {
    id: 'boundary-b-a2a3-systems-biology-readout-operational-definition-review',
    node: 'A2/A3',
    status: 'active',
    priority: 116,
    knowledgeKeywords: ['系统生物学', '合成生物学', '基因回路', '动态阈值', '迟滞', '报告蛋白', '读出口径'],
    questionTypes: ['系统生物学动态题审核', '合成生物学题审核', '多读出通道审核'],
    logicPatterns: ['审核读出口径资格', '审核阈值定义来源', '审核成熟报告滞后', '审核状态历史可达性'],
    triggerKeywords: ['MS2', 'nascent RNA', '成熟荧光', 'GFP', 'bulk', '流式', '阈值', '状态边界', '迟滞', '读出'],
    promptSnippet: '审核系统生物学/合成生物学动态题时，必须检查标准解是否先锁定阈值和状态边界的 operational definition，并说明各读出通道的时间尺度和资格。若答案把成熟荧光、bulk蛋白或流式门控直接替代即时转录/当前阈值状态，或引入题干未授权的外部阈值、表观迟滞参数来支撑结论，应判为critical issue；若只做显式on/off阈值或传递函数代入而没有状态可达性和读出口径分叉，应判为depthIssue。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-11'],
    effect: 'useful',
    effectReason: '与A1系统生物学读出口径规则配套，防止审核端把显式阈值代入或成熟报告蛋白直读误判为有效动态机制推理。',
  },
  {
    id: 'boundary-legacy-a1-hdx-ex2-comparability-and-units',
    node: 'A1',
    status: 'active',
    priority: 103,
    knowledgeKeywords: ['HDX-MS', 'EX2', '保护因子', 'PF', 'RT ln', '结构生物学', '自由能'],
    questionTypes: ['HDX-MS保护自由能题', '结构生物学定量判读题'],
    logicPatterns: ['EX2可比条件先行', '同肽段同条件才可比', 'cal/kcal/kJ单位链闭合', '结构证据不得替代定量阈值'],
    triggerKeywords: ['EX2', 'PF=kint/kobs', 'RT ln', 'cal', 'kcal', 'kJ', '单峰', '单指数', 'pH', '温度', 'kint'],
    promptSnippet: '生成HDX-MS保护因子题时，只有在EX2、同肽段、同pH/温度、kint/kobs单位统一且单峰/单指数可比时，才允许用PF比值与RT ln(PF比值)比较自由能；必须让R的单位一路贯穿到功能阈值单位。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-06-05'],
    effect: 'useful',
    effectReason: '历史分析中HDX题既有低区分度区间也有单位和适用性风险，该规则把生成重点转向可比性门控而非显式PF直算。',
  },
  {
    id: 'boundary-legacy-a1-bioenergetic-coupled-branch-po',
    node: 'A1',
    status: 'active',
    priority: 101,
    knowledgeKeywords: ['P/O', '质子泵', '电子传递链', '末端氧化酶', '古菌', '非泵质子旁路', '氧化磷酸化'],
    questionTypes: ['膜生物能量学计量题', '电子传递链分支题', 'P/O计算题'],
    logicPatterns: ['先区分耦联与非耦联分支', '旁路释质子不得计入跨膜泵质子', '残余通量决定有效产能分支'],
    triggerKeywords: ['P/O', 'H+', '质子泵', '旁路', '残余通量', '抑制剂', '末端氧化酶', '电子流', 'ATP合酶'],
    promptSnippet: '生成膜生物能量学或P/O题时，必须先用抑制剂残余通量、副产物比例或电子分支确定有效耦联分支，再按泵质子分支计算产能；旁路氧化酶的化学释质子不得当作跨膜泵质子贡献，除非题干明确定义其跨膜转运。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-05-11'],
    effect: 'useful',
    effectReason: '历史分析指出旁路化学质子释放与跨膜泵质子容易被混同，适合作为生物能量学高防御生成规则。',
  },
  {
    id: 'boundary-legacy-a1-hysteresis-state-history',
    node: 'A1',
    status: 'active',
    priority: 102,
    knowledgeKeywords: ['迟滞', '双稳态', '状态机', 'RET', '复合体I', '历史依赖', '阈值'],
    questionTypes: ['阈值迟滞题', '状态依赖生理题', '时间序列扰动题'],
    logicPatterns: ['保留上一阶段状态历史', '启动阈值与终止阈值分离', '路径依赖不能用静态阈值替代'],
    triggerKeywords: ['θ_on', 'θ_off', '启动', '维持', '终止', '迟滞', '双稳态', '历史状态', '上一阶段'],
    promptSnippet: '生成迟滞或双稳态题时，必须显式保留上一阶段状态：若系统已启动，下一阶段先判断是否达到终止阈值θ_off，而不是重新套启动阈值θ_on；若系统未启动，才判断是否跨过启动阈值。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-05-11'],
    effect: 'useful',
    effectReason: '旧报告多次出现静态阈值替代路径依赖的问题，且与现有base阈值规则互补，提供更具体的θ_on/θ_off链路。',
  },
  {
    id: 'boundary-legacy-a1-bioprocess-byproduct-mass-balance',
    node: 'A1',
    status: 'active',
    priority: 100,
    knowledgeKeywords: ['稳态发酵', '副产物阈值', '米氏清除', '比生长速率', '底物摄取速率', '生化工程'],
    questionTypes: ['生化工程稳态质量衡算题', '发酵副产物阈值题'],
    logicPatterns: ['单位细胞干重基准质量衡算', '未给生物量得率不得自造μ约束', '副产物生成清除闭合'],
    triggerKeywords: ['稳态', '发酵', '副产物', '清除', 'μ', 'Y_X/S', '维护系数', '底物摄取', '细胞干重'],
    promptSnippet: '生成稳态发酵或副产物阈值题时，必须先在单位细胞干重基准下写副产物生成=清除的质量衡算；若题面只给底物比消耗速率，不得让答案自行引入经验生物量得率或维护项来限制μ，除非题干显式给出这些参数。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-05-11'],
    effect: 'useful',
    effectReason: '历史分析指出解题方可能在得到正确中间量后自造未给参数导致终答案漂移，该规则把A1题面边界钉死。',
  },
  {
    id: 'boundary-legacy-a5-final-answer-drift-after-correct-intermediate',
    node: 'A5',
    status: 'active',
    priority: 106,
    knowledgeKeywords: ['稳态发酵', '生化工程', '代谢通量', '质量衡算', '生物'],
    questionTypes: ['盲解裁判', '答案一致性裁判', '中间量裁判'],
    logicPatterns: ['中间正确但最终答案漂移', '自造未给参数', '正确关键数值后改写结论'],
    triggerKeywords: ['中间结果', '最终答案', 'Y_X/S', '维护系数', 'μ', '未给参数', '漂移', '质量衡算'],
    promptSnippet: 'A5若发现盲解已经得到标准关键中间量，但随后引入题干未给的生物量得率、维护系数、经验μ限制或额外假设改写最终答案，应判为final_answer_drift_after_correct_intermediate，不能因部分中间步骤正确而放行。',
    source: 'boundary_feedback',
    evidenceCaseIds: ['boundary-analysis-2026-05-11'],
    effect: 'useful',
    effectReason: '旧报告提供了“关键中间量正确但最终答案漂移”的可裁判模式，适合进入A5。',
  },
];
