export type FinanceRuleNode = 'A0' | 'A1' | 'A2/A3' | 'A4' | 'A5';
export type FinanceRuleStatus = 'active' | 'candidate' | 'deprecated';
export type FinanceRuleSource = 'base' | 'model_feedback';
export type FinanceRuleEffect = 'useful' | 'unknown' | 'useless' | 'harmful';

export interface FinanceRule {
    id: string;
    node: FinanceRuleNode;
    status: FinanceRuleStatus;
    priority: number;
    family?: string;
    knowledgeKeywords: string[];
    questionTypes: string[];
    logicPatterns: string[];
    triggerKeywords: string[];
    requireAny?: string[];
    requireAll?: string[];
    positiveTriggers?: string[];
    negativeTriggers?: string[];
    promptSnippet: string;
    source: FinanceRuleSource;
    evidenceCaseIds: string[];
    effect: FinanceRuleEffect;
    effectReason: string;
}

/**
 * 量化金融规则库
 *
 * 定位：本库的重心是**把题目难度顶到博士级**，而不是埋陷阱。
 * 每条 promptSnippet 描述的都是"该方向上博士级题目必须跨过的那道推导门槛"，
 * 由 rule-matcher 按节点（A0 规划 / A1 生题 / A2A3 审查 / A4 盲解 / A5 裁判）动态注入。
 */
export const FINANCE_RULE_BANK: FinanceRule[] = [
    // ══════════════════════════════════════════════════════════════════
    // A0：考察维度规划与方向路由
    // ══════════════════════════════════════════════════════════════════
    {
        id: 'base-a0-doctoral-depth-planning',
        node: 'A0',
        status: 'active',
        priority: 92,
        family: 'a0-doctoral-planning',
        knowledgeKeywords: ['金融'],
        questionTypes: ['计算题', '推导题', '论证题', '博士级规划'],
        logicPatterns: ['模型适用域判定', '多层量区分', '推导链闭合', '反教材模板'],
        triggerKeywords: ['金融'],
        promptSnippet: '规划考察维度时以博士资格考/顶刊复现的深度为基准：每个维度必须要求先判定模型适用域或测度/口径归属，再完成至少两个概念交叉的多步推导，且存在一个"外观相似但定义不同"的量（表观/本征、名义/实际、隐含/瞬时、总量/边际）。禁止规划出可由单一公式一步代入的维度。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: 'A0 通用博士级深度基线，抑制单公式代入型维度。',
    },
    {
        id: 'base-a0-derivatives-domain-routing',
        node: 'A0',
        status: 'active',
        priority: 90,
        family: 'a0-derivatives-routing',
        knowledgeKeywords: ['期权定价', '衍生品', '波动率', '对冲', '希腊值'],
        questionTypes: ['衍生品泛知识点路由'],
        logicPatterns: ['测度/计价单位分流', '曲面三层量区分', '对冲误差分解'],
        triggerKeywords: ['期权', '衍生品', '波动率', '对冲', 'Delta', 'Gamma', 'Vega'],
        requireAny: ['期权', '衍生品', '波动率', '对冲', 'Greeks', '希腊值'],
        positiveTriggers: ['Black-Scholes', 'BSM', '风险中性', 'Girsanov', '测度变换', '计价单位', 'numéraire', 'Dupire', 'SABR', 'Heston', '局部波动率', '隐含波动率', 'LSM', '二叉树'],
        promptSnippet: '若只输入泛衍生品知识点，A0 须先分流方向：测度变换/计价单位切换（Girsanov、T-远期测度、股价测度）、波动率三层量（隐含/局部/瞬时，Dupire 与 SABR）、离散对冲 P&L 分解（Gamma-Vega 交叉项）、美式与路径依赖数值方法（LSM 前视偏差、二叉树收敛方向）。维度中必须保留标准术语，禁止只写"期权定价计算"。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '让泛衍生品输入在 A0 就落到具体的博士级模型边界。',
    },
    {
        id: 'base-a0-term-structure-credit-routing',
        node: 'A0',
        status: 'active',
        priority: 90,
        family: 'a0-term-structure-routing',
        knowledgeKeywords: ['期限结构', '利率衍生品', '收益率曲线', '信用衍生品', '久期'],
        questionTypes: ['利率与信用泛知识点路由'],
        logicPatterns: ['曲线自举与折现曲线分离', '凸性调整判定', '强度模型与结构模型分流'],
        triggerKeywords: ['期限结构', '收益率曲线', '利率', '久期', 'CDS', '信用', '互换'],
        requireAny: ['期限结构', '收益率曲线', '久期', 'CDS', '信用价差', '互换', '利率衍生品'],
        positiveTriggers: ['bootstrap', 'OIS', 'SOFR', '双曲线', 'HJM', 'Hull-White', 'Vasicek', 'CIR', 'LMM', '凸性调整', 'DV01', '危险率', 'hazard', '强度模型', 'Merton模型', '回收率', 'CVA'],
        promptSnippet: '若只输入泛利率/信用知识点，A0 须分流到：多曲线自举（OIS 折现 vs 远期曲线，抵押品口径）、凸性调整与测度不匹配（远期利率≠期货利率、CMS）、短期利率模型标定（Hull-White/Vasicek/CIR 与 Feller 条件）、久期-凸性的二阶展开失效域、信用强度模型 vs Merton 结构模型的违约概率口径（风险中性 vs 真实世界）、回收率与 CVA 的错向风险。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '覆盖利率与信用两条最容易被写成单公式代入的主线。',
    },
    {
        id: 'base-a0-valuation-corporate-routing',
        node: 'A0',
        status: 'active',
        priority: 89,
        family: 'a0-valuation-routing',
        knowledgeKeywords: ['估值', '企业估值', '资本结构', '资本预算', '公司理财', '投资银行'],
        questionTypes: ['估值与公司理财泛知识点路由'],
        logicPatterns: ['现金流与折现率配对', '杠杆路径依赖', '实物期权与NPV分叉'],
        triggerKeywords: ['估值', 'DCF', 'WACC', 'FCFF', 'FCFE', '资本结构', 'NPV', 'IRR', 'LBO'],
        requireAny: ['估值', 'DCF', 'WACC', 'FCFF', 'FCFE', '资本结构', '资本预算', 'NPV', 'IRR', 'LBO', '并购'],
        positiveTriggers: ['APV', 'MM定理', '税盾', '去杠杆beta', '重加杠杆', '永续增长', '终值', '多重IRR', 'MIRR', '实物期权', '协同效应', '摊薄', '瀑布分配'],
        promptSnippet: '若只输入泛估值/公司理财知识点，A0 须分流到：现金流口径与折现率的严格配对（FCFF↔WACC、FCFE↔k_e、股利↔k_e，名义↔名义）、杠杆时变下的 APV vs 逐期 WACC（路径依赖，常数 WACC 失效）、beta 的去杠杆/重加杠杆链与 Hamada 前提、终值假设的自洽性（g<WACC、终值占比、退出乘数与永续法交叉验证）、多重 IRR 与 MIRR 的判别、实物期权对 NPV 决策的反转。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '估值题最易退化为教材式 DCF 代入，需在 A0 就锚定配对与路径依赖。',
    },
    {
        id: 'base-a0-econometrics-routing',
        node: 'A0',
        status: 'active',
        priority: 89,
        family: 'a0-econometrics-routing',
        knowledgeKeywords: ['计量经济', '时间序列', '因果推断', '面板数据', '横截面'],
        questionTypes: ['计量泛知识点路由'],
        logicPatterns: ['原假设方向判定', '识别策略前置', '渐近分布退化'],
        triggerKeywords: ['计量', '时间序列', '回归', '因果', '面板', 'GARCH', 'ADF', '协整', 'IV', 'DID'],
        requireAny: ['计量', '时间序列', '回归', '因果推断', '面板', 'GARCH', 'ADF', '协整', '工具变量', '双重差分'],
        positiveTriggers: ['单位根', 'KPSS', 'Johansen', '误差修正', 'VAR', 'Granger', '伪回归', '弱工具', '2SLS', '平行趋势', 'RDD', 'GMM', '聚类标准误', 'Diebold-Mariano'],
        promptSnippet: '若只输入泛计量知识点，A0 须分流到：单位根与协整的原假设方向（ADF 原假设=有单位根，KPSS 原假设=平稳；非标准分布不能用常规 t 临界值）、伪回归与误差修正的判别链、GARCH 族的参数约束与矩存在条件（平稳性 α+β<1、四阶矩条件）、识别策略的可信性（弱工具首段 F、排他性约束、平行趋势可检验含义、聚类层级）。维度必须要求解题者自行选择并论证识别策略，而非题面指定。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '计量题的博士级难点在原假设方向与识别论证，不在算术。',
    },
    {
        id: 'base-a0-actuarial-risk-routing',
        node: 'A0',
        status: 'active',
        priority: 89,
        family: 'a0-actuarial-routing',
        knowledgeKeywords: ['精算', '寿险', '非寿险', '准备金', '风险度量', '损失分布'],
        questionTypes: ['精算与风险泛知识点路由'],
        logicPatterns: ['分数年龄假设互斥', '重尾矩存在性', '风险度量一致性'],
        triggerKeywords: ['精算', '寿险', '年金', '准备金', '免赔额', 'VaR', 'TVaR', '再保险', '信度'],
        requireAny: ['精算', '寿险', '非寿险', '年金', '准备金', '免赔额', 'VaR', 'TVaR', '再保险', '信度', '损失分布'],
        positiveTriggers: ['生命表', '死亡率', 'UDD', 'Balducci', '常数死力', 'Thiele', '复合泊松', '帕累托', 'Pareto', 'GPD', '极值理论', '链梯法', 'Bornhuetter-Ferguson', 'Bühlmann', 'Lundberg'],
        promptSnippet: '若只输入泛精算/风险知识点，A0 须分流到：分数年龄假设的互斥选择（UDD / 常数死力 / Balducci 给出不同数值，必须唯一）、递归准备金（Thiele/Fackler）与保费分解、复合分布的矩与卷积（免赔额同时改变频率与强度）、重尾分布的矩存在性（Pareto α≤2 时方差不存在，α≤1 时均值不存在）与 EVT 阈值选择、风险度量的一致性公理（VaR 不次可加、TVaR 次可加）、信度理论的 Z∈[0,1] 与 Bühlmann-Straub 结构参数估计。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '精算题的博士级门槛集中在假设互斥性与矩存在性，两者都易被跳过。',
    },
    {
        id: 'base-a0-international-fx-routing',
        node: 'A0',
        status: 'active',
        priority: 88,
        family: 'a0-fx-routing',
        knowledgeKeywords: ['国际金融', '汇率', '外汇', '利率平价', '国际收支'],
        questionTypes: ['国际金融泛知识点路由'],
        logicPatterns: ['标价方向判定', '平价条件层级', '跨货币基差'],
        triggerKeywords: ['汇率', '外汇', '利率平价', 'CIP', 'UIP', 'PPP', 'quanto', '国际收支'],
        requireAny: ['汇率', '外汇', '利率平价', 'CIP', 'UIP', 'PPP', 'quanto', '国际收支', '货币互换'],
        positiveTriggers: ['直接标价', '间接标价', '基准货币', '报价货币', '掉期点', '抛补', '无抛补', '跨货币基差', '三角套汇', '风险逆转', '远期溢价之谜', 'carry trade'],
        promptSnippet: '若只输入泛国际金融知识点，A0 须分流到：标价方向与基准/报价货币的显式约定（方向错误会使结论符号反转）、平价条件的层级与可检验性（CIP 近似无套利但含跨货币基差，UIP 与 PPP 是均衡条件而非无套利）、quanto 与跨货币产品的相关性必要性、三角套汇的交易成本闭合、外汇敞口三类（交易/折算/经济）的区分。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '汇率题一旦不声明标价方向即无唯一解，须在 A0 前置。',
    },
    {
        id: 'base-a0-statement-analysis-routing',
        node: 'A0',
        status: 'active',
        priority: 87,
        family: 'a0-statement-routing',
        knowledgeKeywords: ['财务管理', '财务分析', '财务报表', '盈余管理'],
        questionTypes: ['财务分析泛知识点路由'],
        logicPatterns: ['三表联动闭合', '会计政策可比性调整', '权责发生制与现金流背离'],
        triggerKeywords: ['财务报表', '资产负债表', '现金流量表', '杜邦', '应计', '折旧', '租赁'],
        requireAny: ['财务报表', '财务分析', '资产负债表', '现金流量表', '杜邦', '应计', '折旧', '存货计价', '租赁'],
        positiveTriggers: ['三表联动', '权责发生制', '收入确认', 'FIFO', 'LIFO', '资本化', '费用化', '递延所得税', '表外融资', 'ROE分解', 'ROIC', '现金转换周期', '盈余管理'],
        promptSnippet: '若只输入泛财务分析知识点，A0 须分流到：三表联动的强制闭合（净利润→留存收益→资产负债表恒等式，间接法调节项完整）、会计政策差异下的可比性调整（资本化 vs 费用化、FIFO vs LIFO、经营 vs 融资租赁必须先调至同一口径再比较）、权责发生制与现金流的系统性背离（应计质量、现金转换周期）、杜邦分解的层级一致性与 ROIC 口径（分子税后经营利润须与分母投入资本匹配）。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '报表题必须靠恒等式闭合与口径调整拉开难度。',
    },
    // ══════════════════════════════════════════════════════════════════
    // A1：生题（把难度顶到博士级的具体门槛）
    // ══════════════════════════════════════════════════════════════════
    {
        id: 'base-a1-doctoral-difficulty-floor',
        node: 'A1',
        status: 'active',
        priority: 95,
        family: 'a1-difficulty-floor',
        knowledgeKeywords: ['金融'],
        questionTypes: ['计算题', '推导题', '论证题'],
        logicPatterns: ['多步依赖链', '适用域判定前置', '结论可被判定错'],
        triggerKeywords: ['金融'],
        promptSnippet: '难度地板（博士级）：解题链须有 ≥5 个相互依赖的实质步骤，其中至少一步是"判定后才知道走哪条路"的模型/口径适用域判断，且该判断错误会导致数值量级或结论方向改变。禁止出"已知 A、B 求 C"的单公式代入题，禁止把应由解题者判定的前提写进题面。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: 'A1 通用难度地板，是本库的核心目标而非陷阱设计。',
    },
    {
        id: 'base-a1-measure-numeraire-depth',
        node: 'A1',
        status: 'active',
        priority: 93,
        family: 'a1-measure-numeraire',
        knowledgeKeywords: ['期权定价', '风险中性', '测度变换', '计价单位', '随机利率'],
        questionTypes: ['测度变换推导题'],
        logicPatterns: ['漂移修正', '折现因子不可外提', '鞅性质构造'],
        triggerKeywords: ['风险中性', '测度', 'Girsanov', '计价单位', 'numéraire', '远期测度', '随机利率'],
        requireAny: ['测度', 'Girsanov', '计价单位', 'numéraire', '风险中性', '远期测度'],
        positiveTriggers: ['T-远期测度', '股价测度', 'quanto', '漂移', '鞅', '相关系数'],
        promptSnippet: '测度/计价单位方向的博士级门槛：题目须让解题者自行判断哪个计价单位使目标量成为鞅。随机利率且标的与利率相关时，exp(−∫r ds) 不可作为常数移出期望——正确路径必须换到 T-远期测度、由 Girsanov 得到漂移修正、再乘 P(0,T)。测度变换只改漂移不改扩散；quanto/best-of 须显式写出换测度后的漂移。题面给出相关系数与利率波动率但不提示"需换测度"。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '测度变换是衍生品方向最能拉开博士级差距的门槛。',
    },
    {
        id: 'base-a1-volatility-three-layer-depth',
        node: 'A1',
        status: 'active',
        priority: 93,
        family: 'a1-volatility-layers',
        knowledgeKeywords: ['波动率', '隐含波动率', '局部波动率', '波动率曲面'],
        questionTypes: ['波动率曲面反演题'],
        logicPatterns: ['无套利检验前置', '斜率2倍关系', '三层量区分'],
        triggerKeywords: ['隐含波动率', '局部波动率', '瞬时波动率', '波动率微笑', '曲面', 'Dupire', 'SABR'],
        requireAny: ['隐含波动率', '局部波动率', '波动率曲面', '波动率微笑', 'Dupire', 'SABR', '偏斜'],
        positiveTriggers: ['蝶式', '日历价差', '无套利', '斜率', 'backbone', 'β', 'ρ', 'ν'],
        promptSnippet: '波动率方向的博士级门槛：必须区分隐含/局部/瞬时三层量。σ_imp²(T)·T=∫₀ᵀσ²(t)dt 只在确定性波动率下成立，隐含波动率序列不能算术平均；近 ATM 局部波动率斜率≈2×隐含波动率斜率，不可互代入 Dupire 型 PDE；用 Dupire 前必须先检验日历价差 ∂C/∂T≥0 与蝶式 ∂²C/∂K²>0，分母趋零/为负说明报价含套利。SABR 须先由 backbone 定 β 再校准 ρ、ν（β 与 ρ 对 ATM 斜率的贡献可相互抵消，区间内拟合好但外推失效）。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '三层波动率混淆是该方向最高频的深度失分点。',
    },
    {
        id: 'base-a1-hedging-pnl-decomposition-depth',
        node: 'A1',
        status: 'active',
        priority: 91,
        family: 'a1-hedging-pnl',
        knowledgeKeywords: ['对冲', '希腊值', '离散对冲', 'Delta', 'Gamma', 'Vega'],
        questionTypes: ['对冲P&L分解题'],
        logicPatterns: ['方差与成本反向权衡', '粘性假设分叉', 'Vega不可跨期加总'],
        triggerKeywords: ['对冲', 'Delta', 'Gamma', 'Vega', '再平衡', '交易成本', 'P&L'],
        requireAny: ['对冲', 'Delta对冲', 'Gamma', 'Vega', '再平衡', '希腊值'],
        positiveTriggers: ['粘性行权价', '粘性Delta', 'sticky', '离散', '交易成本', '实现波动率', '频率'],
        promptSnippet: '对冲方向的博士级门槛：P&L 须分解为 Gamma 项（∝Γ S²(σ_realized²−σ_imp²)Δt）、Vega 项与成本项。对冲误差方差 ∝Δt 而累计交易成本 ∝1/√Δt，故存在内点最优频率——"频率越高越好"是错误结论。有偏斜时 Δ_total=Δ_BS+Vega·∂σ_imp/∂S，粘性行权价与粘性 Delta 给出方向相反的修正，须由市场实证特征判定适用哪一种。不同期限 Vega 不可直接相加。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '把对冲题从"算希腊值"提升到"权衡与假设判定"。',
    },
    {
        id: 'base-a1-curve-bootstrap-convexity-depth',
        node: 'A1',
        status: 'active',
        priority: 92,
        family: 'a1-curve-convexity',
        knowledgeKeywords: ['期限结构', '收益率曲线', '互换', '凸性调整', '久期'],
        questionTypes: ['曲线自举与凸性题'],
        logicPatterns: ['双曲线折现分离', '测度不匹配调整', '二阶展开失效'],
        triggerKeywords: ['bootstrap', '自举', '收益率曲线', 'OIS', 'SOFR', '凸性调整', '久期', 'DV01', 'CMS'],
        requireAny: ['自举', 'bootstrap', '收益率曲线', '期限结构', '凸性调整', '久期', 'DV01', '互换'],
        positiveTriggers: ['双曲线', '折现曲线', '远期曲线', '抵押品', '期货利率', 'CMS', '修正久期', '关键期限'],
        promptSnippet: '曲线方向的博士级门槛：折现曲线与远期曲线必须分离（抵押品口径决定折现曲线，OIS/SOFR 折现），单曲线自举在含基差市场会产生系统性偏差。远期利率≠期货利率、CMS 与远期互换利率之间存在凸性调整，其根源是测度不匹配而非"经验修正"，须显式给出符号与量级。久期-凸性二阶展开在大幅平行移动或非平行移动下失效，须用关键期限久期或全额重定价交叉验证；组合久期加总须以市值加权而非面值。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '曲线题最易退化为"查表算久期"，需靠双曲线与凸性拉深。',
    },
    {
        id: 'base-a1-credit-default-measure-depth',
        node: 'A1',
        status: 'active',
        priority: 91,
        family: 'a1-credit-measure',
        knowledgeKeywords: ['信用', 'CDS', '违约概率', '危险率', '回收率'],
        questionTypes: ['信用违约概率反演题'],
        logicPatterns: ['风险中性与真实世界口径', '强度与结构模型分叉', '错向风险'],
        triggerKeywords: ['CDS', '违约概率', '危险率', 'hazard', '信用价差', '回收率', 'CVA', 'Merton模型'],
        requireAny: ['CDS', '违约概率', '危险率', '信用价差', '回收率', 'CVA', '强度模型'],
        positiveTriggers: ['风险中性违约概率', '真实世界违约概率', '生存概率', '结构化模型', '错向风险', 'wrong-way', '抵押品'],
        promptSnippet: '信用方向的博士级门槛：由 CDS 价差反解的是风险中性违约概率，与评级迁移矩阵给出的真实世界违约概率相差一个风险溢价倍数（历史上 2-10 倍），两者不可混用；回收率与违约概率在价差中同时出现，仅由单一价差无法唯一分离，须给出独立约束或做敏感性。强度模型与 Merton 结构模型给出不同的短期限违约概率形态（结构模型短期趋零），须由题面证据选择。CVA 须体现暴露与违约的相关性（错向风险），不可用独立假设简单相乘。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '两种违约概率口径混用是信用题最致命且最常见的深度缺陷。',
    },
    {
        id: 'base-a1-cashflow-discount-pairing-depth',
        node: 'A1',
        status: 'active',
        priority: 93,
        family: 'a1-cashflow-pairing',
        knowledgeKeywords: ['估值', 'DCF', 'WACC', 'FCFF', 'FCFE', '资本成本'],
        questionTypes: ['估值配对与路径依赖题'],
        logicPatterns: ['现金流折现率配对', '杠杆路径依赖', '终值自洽'],
        triggerKeywords: ['DCF', 'WACC', 'FCFF', 'FCFE', '股权成本', '终值', '永续增长', 'APV'],
        requireAny: ['DCF', 'WACC', 'FCFF', 'FCFE', '资本成本', '终值', '企业估值'],
        positiveTriggers: ['APV', '税盾', '去杠杆', '重加杠杆', 'Hamada', '目标杠杆', '名义', '实际', 'Fisher', '退出乘数'],
        promptSnippet: '估值方向的博士级门槛：现金流与折现率必须严格配对（FCFF↔WACC 得企业价值、FCFE↔k_e 得股权价值、股利↔k_e；名义↔名义、实际↔实际经 Fisher 换算），配错即量级错误。杠杆比率逐期变化时常数 WACC 失效，正确路径是 APV（无杠杆价值+税盾现值，税盾折现率须与其风险匹配）或逐期重算 WACC——两法在同一题下须能交叉验证。终值须自洽：g<WACC、g 不超过长期名义 GDP 增速、终值占比过高须用退出乘数交叉检验。beta 去杠杆/重加杠杆须声明 Hamada 前提（债务 beta、税率恒定）。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '配对错误与常数 WACC 是估值题最高频的量级级错误。',
    },
    {
        id: 'base-a1-capital-budgeting-depth',
        node: 'A1',
        status: 'active',
        priority: 89,
        family: 'a1-capital-budgeting',
        knowledgeKeywords: ['资本预算', 'NPV', 'IRR', '实物期权', '增量现金流'],
        questionTypes: ['资本预算决策反转题'],
        logicPatterns: ['多重IRR判别', '增量口径闭合', '实物期权反转NPV'],
        triggerKeywords: ['NPV', 'IRR', '多重IRR', 'MIRR', '实物期权', '沉没成本', '互斥项目', '不等寿命'],
        requireAny: ['NPV', 'IRR', '资本预算', '实物期权', '互斥项目', '增量现金流'],
        positiveTriggers: ['符号变化', '再投资假设', '等年值', '侵蚀效应', '机会成本', '折旧税盾', '营运资本', '延迟期权', '放弃期权'],
        promptSnippet: '资本预算方向的博士级门槛：现金流序列多次变号时 IRR 不唯一或不存在，须判别后改用 NPV/MIRR 并说明再投资假设差异；增量现金流须完整闭合（含营运资本变动与回收、折旧税盾、机会成本与侵蚀效应，排除沉没成本与已发生的分摊费用）。互斥且不等寿命项目须用等年值或重置链比较。含延迟/扩张/放弃期权时，静态 NPV 为负的项目可能因期权价值转为可行——决策方向须能被期权价值反转，且期权价值须用可辨识的波动率来源估计。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '让资本预算题的结论方向依赖判定而非算术。',
    },
    {
        id: 'base-a1-timeseries-inference-depth',
        node: 'A1',
        status: 'active',
        priority: 91,
        family: 'a1-timeseries-inference',
        knowledgeKeywords: ['时间序列', '单位根', '协整', 'GARCH', '伪回归'],
        questionTypes: ['时间序列推断题'],
        logicPatterns: ['原假设方向', '非标准分布', '矩存在条件'],
        triggerKeywords: ['ADF', 'KPSS', '单位根', '协整', '误差修正', 'GARCH', '伪回归', 'Granger'],
        requireAny: ['ADF', 'KPSS', '单位根', '协整', 'GARCH', '伪回归', '时间序列', 'Granger'],
        positiveTriggers: ['Johansen', '误差修正', 'ECM', '平稳', '差分', '结构突变', '四阶矩', '持续性', 'Diebold-Mariano'],
        promptSnippet: '时间序列方向的博士级门槛：ADF 原假设为"存在单位根"、KPSS 原假设为"平稳"，两者结论方向相反且不能互换；单位根检验统计量服从非标准（Dickey-Fuller）分布，禁止用常规 t 临界值。非平稳序列直接回归会产生伪回归（R² 高、DW 低），须先判协整再建 ECM。GARCH 须检验 α+β<1（协方差平稳）与四阶矩条件（否则峰度不存在，标准误失效）；波动率预测的持续性与半衰期须由 α+β 推出。Granger 因果是预测性而非结构因果。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '原假设方向与分布非标准性是计量题最本质的深度门槛。',
    },
    {
        id: 'base-a1-causal-identification-depth',
        node: 'A1',
        status: 'active',
        priority: 91,
        family: 'a1-causal-identification',
        knowledgeKeywords: ['因果推断', '工具变量', '双重差分', '断点回归', '面板数据'],
        questionTypes: ['识别策略论证题'],
        logicPatterns: ['识别假设可检验性', '弱工具偏误方向', '估计量含义差异'],
        triggerKeywords: ['工具变量', 'IV', '2SLS', '双重差分', 'DID', 'RDD', '固定效应', '内生性', 'GMM'],
        requireAny: ['工具变量', 'IV', '双重差分', 'DID', 'RDD', '内生性', '固定效应', '因果推断'],
        positiveTriggers: ['弱工具', '首段F', '排他性', '过度识别', 'Sargan', 'Hansen', '平行趋势', 'LATE', 'ATT', '聚类', '安慰剂'],
        promptSnippet: '因果识别方向的博士级门槛：题目须让解题者自行提出并论证识别策略。弱工具（首段 F<10）下 2SLS 偏误方向趋向 OLS 且标准误失真，须给出量化判断；排他性约束不可检验，只能论证，过度识别检验只在工具数>内生变量数时可用。DID 的平行趋势只能对处理前时期做可检验的近似，事件研究图的前期系数须联合检验；交错处理下的双向固定效应估计量是各组 ATT 的加权和，权重可为负。IV 估计的是 LATE 而非 ATE，须说明其适用人群。聚类层级须与处理分配层级一致。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '把因果题的难度放在论证而非回归系数计算上。',
    },
    {
        id: 'base-a1-actuarial-assumption-depth',
        node: 'A1',
        status: 'active',
        priority: 90,
        family: 'a1-actuarial-assumption',
        knowledgeKeywords: ['寿险', '精算', '生命表', '准备金', '年金'],
        questionTypes: ['精算假设与递归题'],
        logicPatterns: ['分数年龄假设唯一化', '递归闭合', '保费分解'],
        triggerKeywords: ['生命表', '死亡率', 'UDD', 'Balducci', '常数死力', '准备金', 'Thiele', '年金'],
        requireAny: ['生命表', '死亡率', '准备金', '年金', '精算', 'UDD', '纯保费'],
        positiveTriggers: ['分数年龄', '选择效应', '选择期', 'Thiele', 'Fackler', '递归', '现金价值', '多状态', '多减因', '死亡率改善'],
        promptSnippet: '寿险精算方向的博士级门槛：分数年龄假设（UDD / 常数死力 / Balducci）互斥且给出不同数值，题目须使正确假设可由题面条款唯一确定，禁止并存。必须满足 p_x+q_x=1、0<q_x<1；选择表与终极表的选择期须正确接续。准备金题须走递归（Thiele/Fackler）并与前瞻式/后顾式结果交叉验证，保费须可分解为利差/死差/费差。多状态或多减因模型中各减因强度之和与总强度须一致，且不可把独立减因率直接当从属减因率使用。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '假设互斥与递归闭合是寿险题唯一可解性的前提，也是深度来源。',
    },
    {
        id: 'base-a1-loss-distribution-depth',
        node: 'A1',
        status: 'active',
        priority: 90,
        family: 'a1-loss-distribution',
        knowledgeKeywords: ['非寿险', '损失分布', '重尾', '免赔额', '再保险', '风险度量'],
        questionTypes: ['损失分布与风险度量题'],
        logicPatterns: ['矩存在性判定', '免赔额双重影响', '一致性公理'],
        triggerKeywords: ['帕累托', 'Pareto', '重尾', '免赔额', '责任限额', '再保险', 'VaR', 'TVaR', '复合泊松'],
        requireAny: ['损失分布', '重尾', '免赔额', '再保险', 'VaR', 'TVaR', '复合泊松', '帕累托'],
        positiveTriggers: ['GPD', '极值理论', '阈值', 'Hill', '停止损失', 'LER', '次可加', '一致性风险度量', '链梯法', 'Bühlmann'],
        promptSnippet: '非寿险/风险度量方向的博士级门槛：重尾分布须先判矩存在性（Pareto α≤2 方差不存在、α≤1 均值不存在），矩不存在时禁止用正态近似或 CLT 型置信区间，须改用 EVT/GPD 并说明阈值选择的偏差-方差权衡。免赔额同时改变索赔频率（穿透概率下降）与强度（条件分布右移），只调整其中之一即错误；LER 与限额层的期望须由分层积分得出。风险度量须遵一致性公理：VaR 不满足次可加（可构造组合反例），TVaR≥VaR 且次可加；分位数在离散分布下须声明取值约定。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '矩存在性与免赔额双重影响是该方向最易被跳过的两道门槛。',
    },
    {
        id: 'base-a1-fx-parity-depth',
        node: 'A1',
        status: 'active',
        priority: 89,
        family: 'a1-fx-parity',
        knowledgeKeywords: ['汇率', '外汇', '利率平价', '跨货币'],
        questionTypes: ['汇率平价与套利题'],
        logicPatterns: ['标价方向唯一化', '基差破坏无套利', '相关性必要性'],
        triggerKeywords: ['汇率', 'CIP', 'UIP', 'PPP', '掉期点', '三角套汇', 'quanto', '货币互换'],
        requireAny: ['汇率', '利率平价', 'CIP', 'UIP', 'quanto', '掉期点', '货币互换'],
        positiveTriggers: ['直接标价', '间接标价', '基准货币', '报价货币', '跨货币基差', '抛补', '风险逆转', '折算风险'],
        promptSnippet: '汇率方向的博士级门槛：题面必须使标价方向可由约定唯一确定（基准/报价货币、直接/间接标价），否则结论符号反转；解答须显式声明方向。CIP 在含跨货币基差的市场并不精确成立，基差本身就是题目的深度来源（判断套利是否真实可执行须扣除基差与融资成本）；UIP/PPP 是均衡条件，不能当无套利关系推导远期汇率。quanto 与跨货币产品必须给出相关系数，缺失即不可解。三角套汇须用双边报价并扣交易成本闭合。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '标价方向与跨货币基差决定汇率题的唯一性与深度。',
    },
    {
        id: 'base-a1-statement-articulation-depth',
        node: 'A1',
        status: 'active',
        priority: 88,
        family: 'a1-statement-articulation',
        knowledgeKeywords: ['财务报表', '三表联动', '会计政策', '盈余管理'],
        questionTypes: ['报表联动与可比性题'],
        logicPatterns: ['恒等式闭合', '政策口径统一', '现金流背离'],
        triggerKeywords: ['三表联动', '资产负债表', '现金流量表', '资本化', '费用化', 'FIFO', 'LIFO', '租赁', '递延所得税'],
        requireAny: ['财务报表', '三表联动', '资产负债表', '现金流量表', '资本化', '存货计价', '租赁'],
        positiveTriggers: ['权责发生制', '应计', '间接法', '留存收益', '杜邦', 'ROIC', '表外融资', '现金转换周期'],
        promptSnippet: '财务分析方向的博士级门槛：资产=负债+所有者权益必须严格闭合，净利润须经留存收益贯通三表，间接法调节项（折旧、营运资本变动、非现金损益）须完整且与资产负债表变动一致。跨公司比较前必须先把会计政策调至同一口径（资本化 vs 费用化会同时改变利润、资产与经营/投资现金流的分类；FIFO vs LIFO 在通胀下改变毛利与存货；经营 vs 融资租赁改变负债与 EBITDA），未调整即比较是实质性错误。杜邦分解各层乘积须还原为 ROE，ROIC 分子分母口径须匹配。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '恒等式闭合与口径统一让报表题具备可验证的硬约束。',
    },
    // ══════════════════════════════════════════════════════════════════
    // A2/A3：审查与修复（只拦"不够难"和"不可解"，不拦"没陷阱"）
    // ══════════════════════════════════════════════════════════════════
    {
        id: 'base-a2a3-solvability-closure',
        node: 'A2/A3',
        status: 'active',
        priority: 96,
        family: 'a2a3-solvability',
        knowledgeKeywords: ['金融'],
        questionTypes: ['审查'],
        logicPatterns: ['参数完备性', '唯一解', '口径可判定'],
        triggerKeywords: ['金融'],
        promptSnippet: '可解性审查（最高优先，先于难度）：逐项核对解题所需的每个输入是否都能从题面读出或推出——折现频率与年化约定、日计数基准、复利/连续复利、货币与标价方向、相关系数、税率、假设口径（分数年龄假设、会计政策、贴现曲线）。凡"必须靠猜"的参数一律判为不可解并补入题面；凡"应由解题者判定"的结论（如该用哪条曲线、哪个测度、哪种假设）一律不得写进题面。若存在多组自洽解，须补充唯一化条件。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '不可解题无法进入 A4 盲解，必须先于难度审查处理。',
    },
    {
        id: 'base-a2a3-doctoral-depth-audit',
        node: 'A2/A3',
        status: 'active',
        priority: 94,
        family: 'a2a3-depth-audit',
        knowledgeKeywords: ['金融'],
        questionTypes: ['审查'],
        logicPatterns: ['步骤依赖计数', '判定环节存在性', '单公式退化识别'],
        triggerKeywords: ['金融'],
        promptSnippet: '难度审查（本库核心目标）：判定题目是否达到博士级——(1) 解题链是否有 ≥5 个相互依赖的实质步骤（前一步输出是后一步输入，非并列小问）；(2) 是否存在至少一个"适用域/口径判定"环节，判错会改变数值量级或结论方向；(3) 是否要求解题者自己论证模型选择的合理性或给出失效边界。若题目退化为"代入单一公式"或"查表后乘一个系数"，判为难度不足并要求重构（提高耦合，而不是靠增加数字位数或多加小问）。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '把"难度不足"变成可判定的三条硬指标，而不是主观感受。',
    },
    {
        id: 'base-a2a3-no-arbitrage-consistency',
        node: 'A2/A3',
        status: 'active',
        priority: 93,
        family: 'a2a3-no-arbitrage',
        knowledgeKeywords: ['无套利', '期权', '曲线', '波动率', '定价'],
        questionTypes: ['审查'],
        logicPatterns: ['参数落在可行域', '静态套利检查', '边界条件'],
        triggerKeywords: ['无套利', '期权', '隐含波动率', '收益率曲线', '远期', '平价关系'],
        requireAny: ['无套利', '期权', '波动率', '收益率曲线', '远期', '定价', '互换'],
        positiveTriggers: ['蝶式', '日历价差', 'Dupire', '看跌看涨平价', '边界', '负概率', '贴现因子'],
        promptSnippet: '无套利一致性审查：题面给定的市场数据本身必须无套利。检查隐含波动率曲面是否违反蝶式（凸性）与日历价差（总方差随期限单调不减）条件；贴现因子是否单调且落在 (0,1]；由曲线导出的远期利率是否为负得不合理；期权价格是否满足看跌看涨平价与内在价值/上界边界；相关系数矩阵是否半正定。若给定数据蕴含套利，题目会出现"两条正确路径给出不同答案"，须修正数据而非修正答案。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '套利数据会导致答案不唯一，是 A5 裁判分歧的常见根因。',
    },
    {
        id: 'base-a2a3-unit-convention-audit',
        node: 'A2/A3',
        status: 'active',
        priority: 90,
        family: 'a2a3-unit-convention',
        knowledgeKeywords: ['利率', '收益率', '基点', '年化'],
        questionTypes: ['审查'],
        logicPatterns: ['单位一致', '频率换算', '年化口径'],
        triggerKeywords: ['基点', '年化', '日计数', '复利', '半年付息', '折现频率', '久期'],
        requireAny: ['利率', '收益率', '基点', '年化', '复利', '日计数', '久期', '波动率'],
        positiveTriggers: ['30/360', 'Act/365', 'Act/360', '连续复利', '债券等价收益率', '有效年利率', '开平方时间'],
        promptSnippet: '单位与约定审查：全题的时间单位、利率约定与波动率年化口径须一致且可判定。核对日计数基准（30/360 / Act/360 / Act/365 会给出不同利息）、付息频率与债券等价收益率 vs 有效年利率的换算、离散复利与连续复利的转换、波动率的 √t 缩放（不可线性缩放）、久期的年化与修正久期/麦考利久期的区分、基点与百分比不可混用。任一处不一致都会造成看似小、实则改变答案有效位数的偏差，须在题面或解答中固定。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '约定不一致是金融题最隐蔽的错误来源，且难以在盲解中定位。',
    },
    {
        id: 'base-a2a3-question-text-purity',
        node: 'A2/A3',
        status: 'active',
        priority: 92,
        family: 'a2a3-text-purity',
        knowledgeKeywords: ['金融'],
        questionTypes: ['审查'],
        logicPatterns: ['无解题提示', '无元信息', '自足'],
        triggerKeywords: ['金融'],
        promptSnippet: '题面纯净性审查：题面中不得出现任何解题路径提示或元信息——不得提示"注意测度变换"「需先判断是否协整」之类的方法指引，不得出现"本题考查/难点在于/陷阱是"等命题者视角表述，不得出现步骤编号式引导、答案量级暗示或分值分配说明。题面只允许包含情境、数据、约定与所求。同时题面必须自足：解题所需的每个数值都要在题面中可见（不得只存在于参考答案里）。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '提示性文字会让 A4 盲解失去区分度，使难度评估失真。',
    },
    // ══════════════════════════════════════════════════════════════════
    // A4：盲解自检（只看题面，独立求解时的自我约束）
    // ══════════════════════════════════════════════════════════════════
    {
        id: 'base-a4-declare-convention-first',
        node: 'A4',
        status: 'active',
        priority: 94,
        family: 'a4-declare-convention',
        knowledgeKeywords: ['金融'],
        questionTypes: ['盲解'],
        logicPatterns: ['先声明口径', '再计算'],
        triggerKeywords: ['金融'],
        promptSnippet: '盲解自检：动笔前先把本题的口径显式写出——计价单位与标价方向、利率的复利与日计数约定、波动率年化方式、现金流口径与对应折现率、所用测度及其计价单位。若题面未给定而必须假设，明确标注"假设：…"并说明该假设如何影响结果方向。禁止默认沿用最常见约定而不声明。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '口径未声明时盲解与参考答案的差异无法归因，A5 会误判。',
    },
    {
        id: 'base-a4-model-applicability-check',
        node: 'A4',
        status: 'active',
        priority: 93,
        family: 'a4-applicability',
        knowledgeKeywords: ['金融'],
        questionTypes: ['盲解'],
        logicPatterns: ['适用域判定前置', '失效边界'],
        triggerKeywords: ['金融'],
        promptSnippet: '盲解自检：套用任何公式前先检验其适用条件是否被本题满足——常数参数假设、分布假设、矩存在性、平稳性、无套利、连续交易与无摩擦、小变动线性近似。若条件不满足，说明该公式的偏差方向与量级，并改用适用的方法。凡"公式记得住但用错场景"即为本题的主要失分点。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '博士级题目的核心区分点是适用域判定，而非公式记忆。',
    },
    {
        id: 'base-a4-magnitude-sanity-check',
        node: 'A4',
        status: 'active',
        priority: 90,
        family: 'a4-magnitude',
        knowledgeKeywords: ['金融'],
        questionTypes: ['盲解'],
        logicPatterns: ['量级校验', '边界校验', '符号校验'],
        triggerKeywords: ['金融'],
        promptSnippet: '盲解自检：得出数值后做三重校验——(1) 符号与方向是否符合经济直觉（多头/空头、买入/卖出、升值/贬值）；(2) 量级是否落在合理区间（期权价不超过标的价与行权价折现值给出的上下界、概率与相关系数在合法范围、贴现因子在 (0,1]、波动率非负）；(3) 极端参数下的极限行为是否退化为已知结果。任一校验失败先回查推导而不是直接给出答案。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '量级/边界自检能在盲解阶段拦下大部分推导错误。',
    },
    {
        id: 'base-a4-derivatives-blind-focus',
        node: 'A4',
        status: 'active',
        priority: 89,
        family: 'a4-derivatives-focus',
        knowledgeKeywords: ['期权', '衍生品', '对冲', '波动率', '测度'],
        questionTypes: ['盲解'],
        logicPatterns: ['测度与计价单位配对', '希腊字母不可加'],
        triggerKeywords: ['期权', '期货', '互换', 'Delta', 'Vega', 'Gamma', '波动率', '测度', '鞅'],
        requireAny: ['期权', '衍生品', '对冲', '波动率', '测度', 'Delta', 'Vega', '互换'],
        positiveTriggers: ['Girsanov', '远期测度', '凸性调整', 'SABR', 'Dupire', '离散对冲', '偏斜', '期限结构'],
        promptSnippet: '盲解自检（衍生品）：先确认所选测度与计价单位配对正确，被定价资产除以计价单位后是否为鞅；支付时点与测度期限不匹配时是否需要凸性调整。区分隐含波动率、局部波动率与瞬时波动率，不可互相代入。Vega 不可跨期限直接相加，须按期限桶分别处理；Delta 对冲的残差由 Gamma 与实现-隐含波动率之差驱动，离散对冲下须区分方差项与成本项随再平衡频率的相反走向。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '测度配对与波动率分层是衍生品盲解最易出错处。',
    },
    {
        id: 'base-a4-stats-blind-focus',
        node: 'A4',
        status: 'active',
        priority: 88,
        family: 'a4-stats-focus',
        knowledgeKeywords: ['计量', '检验', '回归', '风险度量'],
        questionTypes: ['盲解'],
        logicPatterns: ['原假设方向', '分布非标准', '矩存在'],
        triggerKeywords: ['检验', '原假设', 'p值', '置信区间', '标准误', 'VaR', 'TVaR', '回归'],
        requireAny: ['检验', '回归', '计量', 'VaR', 'TVaR', '置信区间', '标准误', '分布'],
        positiveTriggers: ['ADF', 'KPSS', '单位根', '弱工具', '聚类', '重尾', '帕累托', '次可加', '峰度'],
        promptSnippet: '盲解自检（统计与风险）：写清原假设与备择假设的方向，确认所用临界值分布是否标准（单位根检验不服从常规 t 分布）；标准误是否需要异方差/自相关/聚类稳健修正。涉及重尾时先判矩是否存在，不存在则禁用正态近似。风险度量须遵守一致性公理（VaR 不次可加、TVaR 次可加），分位数在离散分布下须声明取值约定，且置信水平与持有期的换算不可用 √t 无条件外推。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '假设方向与分布选择错误会让盲解结论整体反转。',
    },
    {
        id: 'base-a4-report-unsolvable-precisely',
        node: 'A4',
        status: 'active',
        priority: 86,
        family: 'a4-unsolvable-report',
        knowledgeKeywords: ['金融'],
        questionTypes: ['盲解'],
        logicPatterns: ['缺参数定位', '不可解归因'],
        triggerKeywords: ['金融'],
        promptSnippet: '盲解自检：若判定题目不可解，必须精确指出缺失的是哪个具体输入（如"缺少两资产相关系数，quanto 调整项无法确定"「未给日计数基准，利息在 30/360 与 Act/365 下不同」），而不是笼统说"信息不足"。若能在明确标注假设后求解，则同时给出"标注假设下的解"与"缺失项清单"，不要只报不可解。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '精确的缺参数定位让 A5 能区分题目缺陷与解题者能力不足。',
    },
    // ══════════════════════════════════════════════════════════════════
    // A5：裁判（参考答案 vs 盲解答案的分歧归因与放行判定）
    // ══════════════════════════════════════════════════════════════════
    {
        id: 'base-a5-attribute-divergence-source',
        node: 'A5',
        status: 'active',
        priority: 95,
        family: 'a5-divergence-attribution',
        knowledgeKeywords: ['金融'],
        questionTypes: ['裁判'],
        logicPatterns: ['分歧归因', '口径差异 vs 实质错误'],
        triggerKeywords: ['金融'],
        promptSnippet: '裁判首要任务：把两份答案的分歧归到确切来源之一——(A) 题面缺失或含糊导致的口径歧义（日计数、复利、标价方向、假设未唯一化）；(B) 参考答案的推导错误；(C) 盲解的推导错误；(D) 两者都对，仅表述或有效位数不同。归因 A 时判定为题目缺陷，须回改题面而不是判盲解错；归因 B 时以盲解为准并修正参考答案。禁止在未定位分歧步骤前直接判定谁对谁错。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '不归因就裁判会把题目缺陷记成解题错误，污染难度评估。',
    },
    {
        id: 'base-a5-numeric-tolerance-policy',
        node: 'A5',
        status: 'active',
        priority: 91,
        family: 'a5-tolerance',
        knowledgeKeywords: ['金融'],
        questionTypes: ['裁判'],
        logicPatterns: ['容差分级', '量级 vs 舍入'],
        triggerKeywords: ['金融'],
        promptSnippet: '数值一致性判定采用分级容差：舍入/中间步骤精度差异（相对误差 <1%，或利率类 <1bp）视为一致；1%—5% 须定位是否源于插值方法、日计数或复利约定差异，属可接受的方法差异则记为"口径差异"而非错误；>5% 或量级不同、符号相反、结论方向相反一律视为实质分歧，必须定位到具体步骤。对概率、相关系数、久期等有量纲/有界量，超出合法范围一律判错，不适用容差。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '统一容差口径可避免把舍入差异误判为错误、把量级差异放过。',
    },
    {
        id: 'base-a5-difficulty-verdict-from-blind',
        node: 'A5',
        status: 'active',
        priority: 93,
        family: 'a5-difficulty-verdict',
        knowledgeKeywords: ['金融'],
        questionTypes: ['裁判'],
        logicPatterns: ['盲解表现反推难度', '区分度'],
        triggerKeywords: ['金融'],
        promptSnippet: '难度裁定（本库核心目标）：用盲解表现反推题目难度。盲解一次直达且未做任何适用域判断 ⇒ 难度不足，建议提高耦合而非加长计算；盲解在"该走哪条路"处发生了实质判断并最终正确 ⇒ 达到目标难度；盲解在判定环节走错但推导自洽 ⇒ 题目难度合格且区分度良好；盲解因题面歧义而失败 ⇒ 题目缺陷，不计为难度。裁判结论中须明确给出这四类之一。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '把难度评估锚定在可观测的盲解行为上，而不是命题者自评。',
    },
    {
        id: 'base-a5-release-label-discipline',
        node: 'A5',
        status: 'active',
        priority: 89,
        family: 'a5-release-label',
        knowledgeKeywords: ['金融'],
        questionTypes: ['裁判'],
        logicPatterns: ['放行分级', '保留意见'],
        triggerKeywords: ['金融'],
        promptSnippet: '放行标签纪律：仅当两份答案实质一致、推导链完整、题面自足且无口径歧义时给 standard；存在可接受的方法/口径差异但结论方向一致时给 with_caveats 并写明保留点；存在多种自洽解读、或结论依赖未唯一化的假设时给 discussion_only；参考答案被修正过、或盲解暴露出推导缺陷但题目本身可救时不得给 standard；题面存在实质缺陷且未修复时给 not_recommended。标签须与已列出的问题清单一致，不得出现"有问题却标 standard"。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '标签与问题清单不一致会让下游误用低质量题目。',
    },
    {
        id: 'base-a5-domain-crosscheck',
        node: 'A5',
        status: 'active',
        priority: 87,
        family: 'a5-domain-crosscheck',
        knowledgeKeywords: ['定价', '曲线', '信用', '估值', '精算'],
        questionTypes: ['裁判'],
        logicPatterns: ['独立路径交叉验证'],
        triggerKeywords: ['期权', '收益率曲线', '信用', 'DCF', '准备金', '互换', 'VaR'],
        requireAny: ['期权', '曲线', '信用', '估值', '准备金', '互换', '定价', 'VaR'],
        positiveTriggers: ['平价关系', '递归', '前瞻式', '后顾式', 'APV', '自举', '交叉验证', '边界'],
        promptSnippet: '裁判交叉验证：尽量用第二条独立路径复核关键数值——期权用看跌看涨平价或边界条件、曲线用自举结果反算已知市场报价、准备金用前瞻式与后顾式互验、估值用 APV 与逐期 WACC 互验、信用用价差反推与强度模型互验。两条路径给出不同结果时，优先怀疑题面给定数据本身不无套利或不自洽，而不是直接判某一方答案错误。',
        source: 'base',
        evidenceCaseIds: [],
        effect: 'unknown',
        effectReason: '独立路径复核是裁判阶段最可靠的判错依据。',
    },
];
